const all_product = [
    {
        id: 'product_S_D_121',
        link: '/allCoffee/coffeeDetail',
        // link_id: '/all_product/121',
        name: '멕시코 치아파스 디카페인',
        taste01: '밸런스',
        taste02: '고소',
        weight: '200',
        price: '16,000',
        cafeName: 'BACS',
        logoImg: 'logo_32.png',
        productImg: 'pd_121.png',
        text_Info: '깔끔한 맛이 일품인 멕시코 치아파스 디카페인입니다. 워터 디카페인 공정을 통해 카페인을 제거했으며 군밤, 은행과도 같은 달달하면서 고소한듯한 향미가 돋보이는 매력적인 커피입니다.',
        info_00: '디카페인  ',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_120',
        link: '/allCoffee/coffeeDetail',
        name: '콜롬비아 후일라 핑크버번 내추럴',
        taste01: '상큼',
        taste02: '과일',
        weight: '200',
        price: '20,000',
        cafeName: 'BACS',
        logoImg: 'logo_32.png',
        productImg: 'pd_120.png',
        text_Info: '열대과일 주스를 마시는 듯한 콜롬비아 핑크버번 내추럴 입니다. 핑크버번은 레드버번과 옐로우 버번의 교배종으로 그 맛과 향이 뛰어납니다. 패션후르츠, 망고, 모히또의 테이스팅 노트를 갖고 있는 화려한 커피입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '강한 산미',
        info_02_p: '신 맛이 강하게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '라이트 미디엄 로스팅  ',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_119',
        link: '/allCoffee/coffeeDetail',
        name: '인디언 헤드',
        taste01: '쌉쌀',
        taste02: '묵직한',
        weight: '200',
        price: '13,000',
        cafeName: '프레이저 커피',
        logoImg: 'logo_31.png',
        productImg: 'pd_119.png',
        text_Info: '다크 초콜릿처럼 깊은 풍미와 단맛이 진하게 감싸는 한국형 클래식 에스프레소',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '콜롬비아 안티오키아 카스틸로 카투라 수프리모 워시드, 브라질 모지아나 내추럴 , 베트남 다크락 G1 로부스타 웻 폴리싱',
        info_04_t: '다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_118',
        link: '/allCoffee/coffeeDetail',
        name: '엘리 크릭',
        taste01: '밸런스',
        taste02: '부드러운',
        weight: '200',
        price: '15,000',
        cafeName: '프레이저 커피',
        logoImg: 'logo_31.png',
        productImg: 'pd_118.png',
        text_Info: '풍부한 단맛과 부드러운 질감을 갖춘 밸런스가 돋보이는 매력적인 커피',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '콜롬비아 칼다스 리사랄다 수프리모 워시드, 브라질 모지아나 NY2 내추럴, 과테말라 안티구아 SHB 버본 워시드, 에티오피아 예가체프 G2 토착종 내추럴',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '직접 무역  ',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_B_117',
        link: '/allCoffee/coffeeDetail',
        name: '레이크 맥켄지',
        taste01: '상큼',
        taste02: '깔끔한',
        weight: '200',
        price: '15,000',
        cafeName: '프레이저 커피',
        logoImg: 'logo_31.png',
        productImg: 'pd_117.png',
        text_Info: '열대과일을 연상시키는 복합적인 산미와 깨끗하고 부드러운 사탕수수의 단맛',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '에티오피아 예가체프 G2 토착종 내추럴, 케냐 니에리 AA 워시드',
        info_04_t: '미디엄 로스팅',
        info_05_t: '공정 무역',
        info_05_p: '농부과 농장에게 공정한 가격으로 구입한 생두입니다.',
    },
    {
        id: 'product_S_116',
        link: '/allCoffee/coffeeDetail',
        name: '콜롬비아 디카페인',
        taste01: '밸런스',
        taste02: '깔끔한',
        weight: '200',
        price: '12,000',
        cafeName: '프레이저 커피',
        logoImg: 'logo_31.png',
        productImg: 'pd_116.png',
        text_Info: '부드럽고 은은한 코코아를 닮은 디카페인 커피',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '싱글 오리진  ',
        info_03_p: '',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_115',
        link: '/allCoffee/coffeeDetail',
        name: '젠틀레인',
        taste01: '초콜릿',
        taste02: '달콤',
        weight: '250',
        price: '12,000',
        cafeName: '브니엘 커피로스터스',
        logoImg: 'logo_30.png',
        productImg: 'pd_115.png',
        text_Info: '헤이즐넛과 초콜릿의 맛이 잘 어울러져 마치 누텔라 초콜릿처럼 부드럽고 깊은 향이 살아있는 커피입니다.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목, 금 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '브라질 상파울루 레인하 펄프드 내추럴, 에티오피아 예가체프 코체레 G1 내추럴',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '직접 무역',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_B_114',
        link: '/allCoffee/coffeeDetail',
        name: '마이 로맨스',
        taste01: '화사한',
        taste02: '꽃향기',
        weight: '250',
        price: '13,000',
        cafeName: '브니엘 커피로스터스',
        logoImg: 'logo_30.png',
        productImg: 'pd_114.png',
        text_Info: '오렌지 향과 마시멜로의 부드러움이 느껴져요. 꿀과 라즈베리의 달콤한 향을 잘 느낄 수있는 커피입니다.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목, 금 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '과테말라 웨웨테낭고 엘 인헤르탈 SHB 워시드, 에티오피아 예가체프 아리차 에얼룸 워시드',
        info_04_t: '미디엄 로스팅',
        info_05_t: '직접 무역',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_S_113',
        link: '/allCoffee/coffeeDetail',
        name: '에티오피아 아리차 스페셜 G1 내추럴',
        taste01: '과일',
        taste02: '꽃향기',
        weight: '250',
        price: '15,000',
        cafeName: '브니엘 커피로스터스',
        logoImg: 'logo_30.png',
        productImg: 'pd_113.png',
        text_Info: '딸기향과 여러 종류의 베리들이 복합적으로 잘 어울리며 생동감 있고 화사해요. 밀크초콜릿의 맛도 잘 살아있는 커피입니다.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목, 금 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '라이트 로스팅 ',
        info_05_t: '직접 무역',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_B_D_113',
        link: '/allCoffee/coffeeDetail',
        name: '젠틀레인 디카페인',
        taste01: '밸런스',
        taste02: '달콤',
        weight: '250',
        price: '13,000',
        cafeName: '브니엘 커피로스터스',
        logoImg: 'logo_30.png',
        productImg: 'pd_112.png',
        text_Info: '깔끔하며 부드러운 단맛이 좋은 디카페인 커피입니다.',
        info_00: '디카페인',
        info_01_t: '매주 화 로스팅  ',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '브라질 세하도 내추럴 스위스워터 디카페인, 에티오피아 지데오 워르카 에얼룸 내추럴 스위스워터 디카페인',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_111',
        link: '/allCoffee/coffeeDetail',
        name: '케냐 AA 워시드',
        taste01: '상큼',
        taste02: '부드러운',
        weight: '250',
        price: '16,000',
        cafeName: '브니엘 커피로스터스',
        logoImg: 'logo_30.png',
        productImg: 'pd_111.png',
        text_Info: '자몽과 라임 그리고 토마토의 향미가 조화롭게 어울려 상큼하고 부드러운 커피입니다. 밸런스가 좋으며 매우 깔끔합니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '라이트 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_110',
        link: '/allCoffee/coffeeDetail',
        name: '안녕잠비',
        taste01: '고소',
        taste02: '묵직한',
        weight: '200',
        price: '14,000',
        cafeName: '안녕 가비 커피로스터스',
        logoImg: 'logo_29.png',
        productImg: 'pd_110.png',
        text_Info: '안녕가비의 시그니쳐블랜딩으로 에스프레소 및 우유가 들어가는 다양한 베리에이션과 잘 조화되는 커피입니다. 풍부한 초콜릿의 단맛과 달콤쌉사래함을 크리미하고 묵직한 바디감과 같이 느낄수 있는 커피입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '에티오피아 시다모 구지 G2 워시드, 콜롬비아 월드 헤리티지 유네스코 워시드, 에티오피아 아리차 에이미 G1 워시드',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_109',
        link: '/allCoffee/coffeeDetail',
        name: '안녕잠비',
        taste01: '상큼',
        taste02: '부드러운',
        weight: '200',
        price: '14,000',
        cafeName: '안녕 가비 커피로스터스',
        logoImg: 'logo_29.png',
        productImg: 'pd_109.png',
        text_Info: '과일사탕을 입안에 머금은 듯한 상큼한산미와 청량감이 함께 느껴지며 새콤달콤한 맛과 향을 가진 개성이 뚜렷한 커피입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '에티오피아 예가체프 아리차 G1 내추럴, 에티오피아 웨스트 아르시 리피사 G1 내추럴, 에티오피아 예가체프 아리차 에이미 워시드',
        info_04_t: '라이트 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_108',
        link: '/allCoffee/coffeeDetail',
        name: '라이카의 여름',
        taste01: '달콤',
        taste02: '깔끔한',
        weight: '200',
        price: '14,000',
        cafeName: '안녕 가비 커피로스터스',
        logoImg: 'logo_29.png',
        productImg: 'pd_108.png',
        text_Info: '부드럽게 퍼지는 은은한산미에 과일시럽같은 단맛, 라즈베리와 멜론의 향이 어울어지며 시트러스한 라임이 후미에 느껴지는 복합성이 뛰어난 커피입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '코스타리카 재규어 브라운허니, 과테말라 라 글로리아, 에티오피아 아리차 에이미 G1 내추럴, 에티오피아 아리차 에이미 G1 워시드',
        info_04_t: '미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_107',
        link: '/allCoffee/coffeeDetail',
        name: '그 해 겨울',
        taste01: '달콤',
        taste02: '부드러운',
        weight: '200',
        price: '14,000',
        cafeName: '안녕 가비 커피로스터스',
        logoImg: 'logo_29.png',
        productImg: 'pd_107.png',
        text_Info: '은은한 산미, 헤이즐넛, 초콜릿의 단맛 등 복합적인 향과 좋은 밸런스를 지닌 커피입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '코스타리카, 과테말라, 에티오피아',
        info_04_t: '미디엄 로스팅',
        info_05_t: '직접 무역',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_B_106',
        link: '/allCoffee/coffeeDetail',
        name: '스테이',
        taste01: '고소',
        taste02: '묵직한',
        weight: '200',
        price: '13,000',
        cafeName: '디벨로핑룸',
        logoImg: 'logo_28.png',
        productImg: 'pd_106.png',
        text_Info: '너무 과하지 않은 배전도로 적절한 쌉싸름함과 스카치 위스키의 몰티함, 초코쿠키의 달달고소함, 깔끔한 밸런스로 어떠한 형태의 커피로든 잘 어울리도록 하였습니다',
        info_00: '',
        info_01_t: '매주 월 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '브라질 미나스 제라이스 카르모 드 미나스 옐로우 버본 내추럴, 콜롬비아 카우카 papayan 워시드, 니카라과 누에바 세고비아 히노떼가 워시드',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_105',
        link: '/allCoffee/coffeeDetail',
        name: '스탠다드룸',
        taste01: '밸런스',
        taste02: '부드러운',
        weight: '200',
        price: '13,000',
        cafeName: '디벨로핑룸',
        logoImg: 'logo_28.png',
        productImg: 'pd_105.png',
        text_Info: '미디엄 로스트의 스탠다드룸은 누구나 편안하게 즐길 수 있는 가장 스탠다드한 블렌드입니다. 2차크랙 직전 배출로 헤비한 느낌보다는 적당히 고소하며 마일드한 커피입니다.',
        info_00: '',
        info_01_t: '매주 월 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '과테말라 안티구아 프리미엄 버본 워시드, 브라질 술 데 미나스 카르모 드 미나스 산타루시아 옐로우 버본',
        info_04_t: '미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_104',
        link: '/allCoffee/coffeeDetail',
        name: '브라질 다테하 빌라',
        taste01: '밸런스',
        taste02: '부드러운',
        weight: '200',
        price: '14,000',
        cafeName: '디벨로핑룸',
        logoImg: 'logo_28.png',
        productImg: 'pd_104.png',
        text_Info: '쓴커피를 벗어날 수 있는 핸드드립 입문자를 위한 밸런스 있는 커피입니다. 긴 잔향과 부담없는 향미로 호불호가 없는 와이칸을 즐겨보세요.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송  ',
        info_01_p: '',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_103',
        link: '/allCoffee/coffeeDetail',
        name: '브라질 다테하 빌라',
        taste01: '견과류',
        taste02: '고소',
        weight: '200',
        price: '12,000',
        cafeName: '디벨로핑룸',
        logoImg: 'logo_28.png',
        productImg: 'pd_103.png',
        text_Info: '고소한 커피를 좋아하신다면 신맛 없이 견과류 가득 느껴지는 브라질 다테하 빌라가 제격입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송  ',
        info_01_p: '',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_102',
        link: '/allCoffee/coffeeDetail',
        name: '콜롬비아 엘 파라이소 리치 더블 무산소',
        taste01: '과일',
        taste02: '꽃향기',
        weight: '200',
        price: '26,000',
        cafeName: '디벨로핑룸',
        logoImg: 'logo_28.png',
        productImg: 'pd_102.png',
        text_Info: '열대과일 쥬스를 마시는 느낌입니다. 여름엔 아이스, 겨울엔 따뜻한 음료 둘 다 어울리는 팔방미인 커피입니다',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송  ',
        info_01_p: '',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '라이트 미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_101',
        link: '/allCoffee/coffeeDetail',
        name: '케냐 구아마 AA TOP 마이크로 랏',
        taste01: '달콤',
        taste02: '상큼',
        weight: '200',
        price: '20,000',
        cafeName: '디벨로핑룸',
        logoImg: 'logo_28.png',
        productImg: 'pd_101.png',
        text_Info: '잘 익은 과일차를 마시는 느낌의 커피입니다. 질감이 부드럽습니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송  ',
        info_01_p: '',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '라이트 미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_D_100',
        link: '/allCoffee/coffeeDetail',
        name: '콜롬비아 E.A 디카페인',
        taste01: '고소',
        taste02: '초콜릿',
        weight: '200',
        price: '16,000',
        cafeName: '디벨로핑룸',
        logoImg: 'logo_28.png',
        productImg: 'pd_100.png',
        text_Info: '디카페인 특유의 향이 많이 나지 않고, 고소하고 부드러운 군고구마 뉘앙스의 커피입니다.',
        info_00: '디카페인',
        info_01_t: '3일 내 볶은 원두만 배송  ',
        info_01_p: '',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_99',
        link: '/allCoffee/coffeeDetail',
        name: '헥사 블렌드',
        taste01: '밸런스',
        taste02: '긴여운',
        weight: '200',
        price: '11,000',
        cafeName: '하우트 커피컴퍼니',
        logoImg: 'logo_27.png',
        productImg: 'pd_99.png',
        text_Info: '헥사는 밸런스에 초점을 맞춘 하우트커피의 시그니처 블렌드입니다. 진한 초콜릿향, 농후한 단맛, 부드러운 산미, 고급스러운 바디감과 실키함까지 커피가 가진 다양한 매력을 만나보세요.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송  ',
        info_01_p: '',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '인도 , 과테말라, 콜롬비아, 에티오피아',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_98',
        link: '/allCoffee/coffeeDetail',
        name: '썸즈업 블렌드',
        taste01: '고소',
        taste02: '쌉쌀',
        weight: '200',
        price: '7,000',
        cafeName: '하우트 커피컴퍼니',
        logoImg: 'logo_27.png',
        productImg: 'pd_98.png',
        text_Info: '다크 초콜렛의 단맛과 견과류의 고소함, 신맛이 적은 것이 특징으로, 고소한 맛을 한번에 표현하는 블렌딩입니다. 썸즈업의 달콤하고 진한 맛은 어떤 베리에이션으로도 잘 어울립니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송  ',
        info_01_p: '',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '과테말라, 브라질, 콜롬비아, 에티오피아',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_97',
        link: '/allCoffee/coffeeDetail',
        name: '디카페인 블렌드',
        taste01: '밸런스',
        taste02: '초콜릿',
        weight: '200',
        price: '12,000',
        cafeName: '하우트 커피컴퍼니',
        logoImg: 'logo_27.png',
        productImg: 'pd_97.png',
        text_Info: '카페인은 안녕, 풍미와 향미는 그대로 화산 빙하의 깨끗한 물과 탄소필터를 활용해 카페인만 99.9% 제거하여, 커피 본연의 풍미와 향을 해치지 않은 마운틴 워터 프로세스의 디카페인 커피입니다.',
        info_00: '디카페인  ',
        info_01_t: '3일 내 볶은 원두만 배송  ',
        info_01_p: '',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '콜롬비아 엑셀소 EP 디카페인, 과테말라 엑셀소 EP 디카페인',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_96',
        link: '/allCoffee/coffeeDetail',
        name: '피타 블렌드',
        taste01: '밸런스',
        taste02: '묵직한',
        weight: '200',
        price: '13,000',
        cafeName: '하우트 커피컴퍼니',
        logoImg: 'logo_27.png',
        productImg: 'pd_96.png',
        text_Info: '잘 익은 살구처럼 산뜻한 과일향, 캐러멜의 진한 단맛이 길게 남는 매력적인 커피입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송  ',
        info_01_p: '',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '과테말라, 콜롬비아, 에티오피아',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '직접 무역',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_S_95',
        link: '/allCoffee/coffeeDetail',
        name: '에티오피아 비샬라 워시드',
        taste01: '상큼',
        taste02: '깔끔한',
        weight: '180',
        price: '19,000',
        cafeName: '카페플롬',
        logoImg: 'logo_26.png',
        productImg: 'pd_95.png',
        text_Info: '복숭아와 은은한 망고스틴 달콤한 여운이 특징입니다',
        info_00: '',
        info_01_t: '매주 수 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '라이트 미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_94',
        link: '/allCoffee/coffeeDetail',
        name: '딥 딥플리 과테말라 엔트레 볼카네스 워시드',
        taste01: '고소',
        taste02: '부드러운',
        weight: '180',
        price: '19,000',
        cafeName: '카페플롬',
        logoImg: 'logo_26.png',
        productImg: 'pd_94.png',
        text_Info: '사과 감귤의 감칠맛을 지닌 산미와 더불어 아몬드와 밀크 초콜릿의 단맛과 고소함이 특징인 커피입니다.',
        info_00: '',
        info_01_t: '매주 수 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_93',
        link: '/allCoffee/coffeeDetail',
        name: '이븐 블렌드',
        taste01: '고소',
        taste02: '묵직한',
        weight: '200',
        price: '11,000',
        cafeName: '오드이븐',
        logoImg: 'logo_25.jpeg',
        productImg: 'pd_93.png',
        text_Info: '고소한 견과류와 묵직한 초콜릿 단맛이 느껴지는 커피로 여운이 길고 밸런스가 좋아요.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '과테말라 웨웨테낭고 SHB 워시드, 에티오피아 시다모 구지 워시드, 콜롬비아 후일라 수프리모 워시드, 브라질 옐로우 버본 NY2 FC 내추럴',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_92',
        link: '/allCoffee/coffeeDetail',
        name: '오드 블렌드',
        taste01: '밸런스',
        taste02: '달콤',
        weight: '200',
        price: '12,000',
        cafeName: '오드이븐',
        logoImg: 'logo_25.jpeg',
        productImg: 'pd_92.png',
        text_Info: '달달한 단감의 단맛이 길게 이어지는 커피로 끝 맛은 진한 홍차처럼 느껴져요.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '에티오피아 예가체프 워시드, 코스타리카 따라주 SHB 워시드, 에티오피아 리무 내추럴, 콜롬비아 후일라 수프리모 워시드',
        info_04_t: '미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_91',
        link: '/allCoffee/coffeeDetail',
        name: '피크 블렌드',
        taste01: '밸런스',
        taste02: '달콤',
        weight: '200',
        price: '10,000',
        cafeName: '오드이븐',
        logoImg: 'logo_25.jpeg',
        productImg: 'pd_91.png',
        text_Info: '고소한 견과류와 카라멜을 함께 먹는것 같은 커피입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '에티오피아 예가체프 내추럴, 과테말라 웨웨테낭고 SHB 워시드, 브라질 모지아나 내추럴 , 콜롬비아 후일라 수프리모 워시드',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_90',
        link: '/allCoffee/coffeeDetail',
        name: '클래식 에스프레소',
        taste01: '밸런스',
        taste02: '고소',
        weight: '200',
        price: '14,000',
        cafeName: '리플렉트 커피 로스터스',
        logoImg: 'logo_24.png',
        productImg: 'pd_90.png',
        text_Info: '카카오를 씹은 듯 쌉싸름한 맛 뒤에 고소한 달콤함이 어우러진 묵직한 커피입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '콜롬비아 나리노 라 유니온 워시드, 브라질 모지아나 내추럴 , 과테말라 안티구아 엔트레 볼카네스 워시드',
        info_04_t: '다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_89',
        link: '/allCoffee/coffeeDetail',
        name: '브릭 에스프레소',
        taste01: '밸런스',
        taste02: '고소',
        weight: '200',
        price: '14,000',
        cafeName: '리플렉트 커피 로스터스',
        logoImg: 'logo_24.png',
        productImg: 'pd_89.png',
        text_Info: '고소한 견과류의 맛과 흑설탕의 단맛 그리고 부드러운 촉감과 완벽한 밸런스를 가진 커피입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '인도 강가기리 워시드, 과테말라 안티구아 엔트레 볼카네스 워시드 , 콜롬비아 라 플라타 워시드',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_D_88',
        link: '/allCoffee/coffeeDetail',
        name: '콜롬비아 디카페인 에스프레소',
        taste01: '달콤',
        taste02: '묵직한',
        weight: '200',
        price: '14,000',
        cafeName: '리플렉트 커피 로스터스',
        logoImg: 'logo_24.png',
        productImg: 'pd_88.png',
        text_Info: '다크 초콜릿의 단맛과 감초의 스파이시함 블랙티의 여운이 좋습니다.',
        info_00: '디카페인  ',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '콜롬비아 카우카 워시드',
        info_04_t: '다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_87',
        link: '/allCoffee/coffeeDetail',
        name: 'BRICK 블랜드',
        taste01: '달콤',
        taste02: '고소',
        weight: '200',
        price: '10,000',
        cafeName: '컬러드 빈',
        logoImg: 'logo_23.jpeg',
        productImg: 'pd_87.png',
        text_Info: '브릭 블랜드는, 정말 좋은 커피 생두들을 선택하여 미디움 다크 배전도로 로스팅 하였습니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '콜롬비아 톨리마 카투라 카스틸로 수프리모 워시드, 에티오피아 시다모 에일룸 G4 내추럴, 브라질 세하도 옐로우 버본 NY2 내추럴',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_86',
        link: '/allCoffee/coffeeDetail',
        name: 'BEIGE 블랜드',
        taste01: '꽃향기',
        taste02: '깔끔한',
        weight: '200',
        price: '12,000',
        cafeName: '컬러드 빈',
        logoImg: 'logo_23.jpeg',
        productImg: 'pd_86.png',
        text_Info: '에티오피아 X 에티오피아 조합으로 굉장히 신선하게 다가오는 맛입니다. 우유와 조합도 굉장히 좋지만, 롱 블랙으로 드셔도 굉장히 좋습니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '에티오피아 예가체프 콩가 에얼룸 G1 내추럴, 에티오피아 예가체프 아다도 에얼룸 G1 워시드',
        info_04_t: '라이트 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_85',
        link: '/allCoffee/coffeeDetail',
        name: '그린 블렌딩 커피',
        taste01: '밸런스',
        taste02: '깔끔한',
        weight: '200',
        price: '7,000',
        cafeName: '링크 커피 로스터스',
        logoImg: 'logo_22.jpeg',
        productImg: 'pd_85.png',
        text_Info: '부드러운 단맛과 고소한 풍미가 밸런스가 좋습니다. 좋은 균형감이 매일 마시기 편안한 커피입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '에티오피아 예가체프 G2 에얼룸 워시드, 콜롬비아 안티오키아 카스틸로 카투라 수프리모 워시드, 브라질 세하도 몬테카르멜로 카투아이 문도노보 NY2 FC 내추럴, 과테말라 산타로사 카투아이 파체 버본 SHB 워시드',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_84',
        link: '/allCoffee/coffeeDetail',
        name: '브라운 블렌딩 커피',
        taste01: '묵직한',
        taste02: '쌉쌀',
        weight: '200',
        price: '7,000',
        cafeName: '링크 커피 로스터스',
        logoImg: 'logo_22.jpeg',
        productImg: 'pd_84.png',
        text_Info: '산미가 거의 없는 진한 다크초콜릿 음료같아요. 풍부한 바다김과 적당한 쌉쌀함이 잘 어울려요.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '콜롬비아 안티오키아 카스틸로 카투라 수프리모 워시드, 브라질 세하도 몬테카르멜로 카투아이 문도노보 NY2 FC 내추럴, 과테말라 산타로사 카투아이 파체 버본 SHB 워시드',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_83',
        link: '/allCoffee/coffeeDetail',
        name: '블렌드 슈퍼 노멀',
        taste01: '밸런스',
        taste02: '쌉쌀',
        weight: '200',
        price: '16,500',
        cafeName: '프로토콜 로스터스',
        logoImg: 'logo_21.jpeg',
        productImg: 'pd_83.png',
        text_Info: '묵직하되 그 묵직함이 과하지 않고 선명한 단맛을 지녔습니다. 다크한 초콜릿 맛과 미미한 산미가 좋은 밸런스를 느끼게 합니다. 데일리 커피로서 역할을 잘 해내리라 자부합니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '콜롬비아 후일라 수프리모, 인도네시아 와하나 만델링 G1, 브라질 산타루시아 펄프드 내추럴',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_82',
        link: '/allCoffee/coffeeDetail',
        name: '클래식 블렌드',
        taste01: '밸런스',
        taste02: '고소',
        weight: '200',
        price: '12,000',
        cafeName: '502 커피로스터스',
        logoImg: 'logo_20.png',
        productImg: 'pd_82.png',
        text_Info: '견과류의 고소한 향미와 묵직한 바디감을 느낄 수 있는 커피입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '인도 마이소르 너겟, 콜롬비아 후일라 몬테벨로, 코스타리카 Coopelibertad',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_81',
        link: '/allCoffee/coffeeDetail',
        name: '공단향 블렌드',
        taste01: '쌉쌀',
        taste02: '달콤',
        weight: '200',
        price: '14,000',
        cafeName: '502 커피로스터스',
        logoImg: 'logo_20.png',
        productImg: 'pd_81.png',
        text_Info: '다크 초콜릿의 진한 단맛과 카카오의 깊은 풍미를 느끼실 수 있어요.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '콜롬비아 나리노 산 안토니오, 에티오피아 게뎁 우리 G1, 케냐 AA Top 니에리',
        info_04_t: '다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_80',
        link: '/allCoffee/coffeeDetail',
        name: '딥씨 블렌드',
        taste01: '밸런스',
        taste02: '달콤',
        weight: '200',
        price: '14,000',
        cafeName: '502 커피로스터스',
        logoImg: 'logo_20.png',
        productImg: 'pd_80.png',
        text_Info: '은은한 산미와 초콜릿의 깊은 단맛이 잘 균형 잡힌 커피입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '콜롬비아 나리노 산 안토니오, 에티오피아 게뎁 우리 G1, 과테말라 와이칸 워시드',
        info_04_t: '미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_79',
        link: '/allCoffee/coffeeDetail',
        name: '콜롬비아 디카페인',
        taste01: '상큼',
        taste02: '달콤',
        weight: '200',
        price: '16,000',
        cafeName: '502 커피로스터스',
        logoImg: 'logo_20.png',
        productImg: 'pd_79.png',
        text_Info: '풍부한 과일의 향미와 밝은 산미를 가진 커피입니다. 맑고 깨끗한 여운을 느끼실 수 있어요.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '에티오피아 게뎁 우리 G1, 에티오피아 예가체프 G1',
        info_04_t: '라이트 미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_78',
        link: '/allCoffee/coffeeDetail',
        name: '콜롬비아 디카페인',
        taste01: '고소',
        taste02: '쌉쌀',
        weight: '200',
        price: '15,000',
        cafeName: '502 커피로스터스',
        logoImg: 'logo_20.png',
        productImg: 'pd_78.png',
        text_Info: '비정제 설탕의 단맛과 토스트 맛이 나요. 카카오의 고소한 향미가 느껴집니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '산미가 없어요 ',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '싱글 오리진 ',
        info_03_p: '',
        info_04_t: '다크 로스팅  ',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_77',
        link: '/allCoffee/coffeeDetail',
        name: '올드타운',
        taste01: '깔끔한',
        taste02: '달콤',
        weight: '200',
        price: '13,000',
        cafeName: '차군커피로스터스',
        logoImg: 'logo_19.png',
        productImg: 'pd_77.png',
        text_Info: '부드러운 단맛이 좋고, 오렌지의 산미가 은은하게 남는 커피입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '약한 산미 ',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '과테말라 리오 아줄 우에우에테낭고 워시드, 콜롬비아 톨리마 플라나다스 워시드',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '공정 무역  ',
        info_05_p: '농부과 농장에게 공정한 가격으로 구입한 생두입니다.',
    },
    {
        id: 'product_B_76',
        link: '/allCoffee/coffeeDetail',
        name: '허클베리',
        taste01: '상큼',
        taste02: '부드러운',
        weight: '200',
        price: '14,000',
        cafeName: '차군커피로스터스',
        logoImg: 'logo_19.png',
        productImg: 'pd_76.png',
        text_Info: '크랜베리 처럼 상큼하고, 달콤한 초콜릿의 여운을 느낄 수 있습니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '새콤한 산미 ',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '과테말라 리오 아줄 우에우에테낭고 워시드, 콜롬비아 톨리마 플라나다스 워시드, 에티오피아 구지 딤투 테로 내추럴',
        info_04_t: '미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_75',
        link: '/allCoffee/coffeeDetail',
        name: '하드워커',
        taste01: '달콤',
        taste02: '쌉쌀',
        weight: '200',
        price: '11,000',
        cafeName: '차군커피로스터스',
        logoImg: 'logo_19.png',
        productImg: 'pd_75.png',
        text_Info: '다크 초콜릿스러운 단맛과 묵직한 바디, 쌉싸름한 후미가 조화를 이룹니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '약한 산미  ',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '브라질 파젠다 과르다 옐로우 버본 펄프드 내추럴, 과테말라 웨웨테낭고 리오아줄 워시드, 인도 아자드힌드 로부스타',
        info_04_t: '다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_D_74',
        link: '/allCoffee/coffeeDetail',
        name: '콜롬비아 수프리모 SW 디카프',
        taste01: '달콤',
        taste02: '고소',
        weight: '200',
        price: '14,000',
        cafeName: '디카프워크룸',
        logoImg: 'logo_18.png',
        productImg: 'pd_74.png',
        text_Info: '비스킷 같은 고소하고 달콤한 향에 부담스럽지 않은 산미가 부드럽게 퍼집니다.',
        info_00: '디카페인',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '약한 산미  ',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_D_73',
        link: '/allCoffee/coffeeDetail',
        name: '에티오피아 G2 시다모 SW 디카프',
        taste01: '과일',
        taste02: '초콜릿',
        weight: '200',
        price: '14,000',
        cafeName: '디카프워크룸',
        logoImg: 'logo_18.png',
        productImg: 'pd_73.png',
        text_Info: '다크초콜릿 같은 달콤쌉싸름한 맛에 오렌지과 산미가 은은하게 개성을 더합니다.',
        info_00: '디카페인',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '가벼운 산미  ',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_D_72',
        link: '/allCoffee/coffeeDetail',
        name: '과테말라 SHB SW 디카프',
        taste01: '견과류',
        taste02: '고소',
        weight: '200',
        price: '14,000',
        cafeName: '디카프워크룸',
        logoImg: 'logo_18.png',
        productImg: 'pd_72.png',
        text_Info: '레몬그라스 같은 독특한 향에 고소한 너트 향, 달콤한 꿀 향이 섞여 풍성하게 다가옵니다.',
        info_00: '디카페인',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '약한 산미  ',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_D_71',
        link: '/allCoffee/coffeeDetail',
        name: 'DCW 블렌드',
        taste01: '밸런스',
        taste02: '달콤',
        weight: '200',
        price: '14,000',
        cafeName: '디카프워크룸',
        logoImg: 'logo_18.png',
        productImg: 'pd_71.png',
        text_Info: '단맛과 고소한 맛을 중심으로 한 방울 떨어뜨린 듯 은은한 산미까지, 풍성한 향미가 둥글게 다가옵니다.',
        info_00: '디카페인',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '콜롬비아 카투라 수프리모 스위스 워터 워시드, 에티오피아 시다모 에얼룸 G2 스위스 워터 워시드, 과테말라 SHB 스위스 워터 워시드',
        info_04_t: '미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_70',
        link: '/allCoffee/coffeeDetail',
        name: '#45-scale',
        taste01: '쌉쌀',
        taste02: '묵직한',
        weight: '250',
        price: '13,500',
        cafeName: '인더매스',
        logoImg: 'logo_17.png',
        productImg: 'pd_70.png',
        text_Info: '다크 초콜릿의 쌉싸름한 풍미와 스모키한 바디감으로 마시고 난 뒤 긴 여운을 느낄 수 있어요.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '과테말라 카투라+카투아이 SHB 워시드, 인도 카피 로얄레 로부스타 Wet-Process, 브라질 세하도 내추럴',
        info_04_t: '다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_69',
        link: '/allCoffee/coffeeDetail',
        name: '#65-scale',
        taste01: '달콤',
        taste02: '상큼',
        weight: '250',
        price: '15,000',
        cafeName: '인더매스',
        logoImg: 'logo_17.png',
        productImg: 'pd_69.png',
        text_Info: '한 잔의 와인을 머금은 듯 느껴지는 베리의 산뜻한 산미와 깔끔한 끝 맛이 마치 잘 고른 티를 우려 낸 것처럼 풍미가 가득합니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '에티오피아 예가체프 첼바 G1 에얼룸 내추럴, 에티오피아 예가체프 콩가 G2 에얼룸 워시드',
        info_04_t: '라이트 미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_68',
        link: '/allCoffee/coffeeDetail',
        name: '#55-scale',
        taste01: '밸런스',
        taste02: '고소',
        weight: '250',
        price: '13,500',
        cafeName: '인더매스',
        logoImg: 'logo_17.png',
        productImg: 'pd_68.png',
        text_Info: '메이플 시럽과 고소한 맛이 느껴져요. 산미가 은은해요. 바디감까지 균형감이 좋은 커피입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '과테말라 카투라+카투아이 SHB 워시드, 콜롬비아 안티오키아 카스틸로 카투라 수프리모 워시드, 브라질 세하도 내추럴',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_67',
        link: '/allCoffee/coffeeDetail',
        name: '극야 블렌드',
        taste01: '쌉쌀',
        taste02: '고소',
        weight: '200',
        price: '13,000',
        cafeName: '오프사이트',
        logoImg: 'logo_16.png',
        productImg: 'pd_67.png',
        text_Info: '다크 초콜릿, 구운 견과류와 무거운 바디감이 특징으로 대중적이고 매일 즐기기 좋은 커피입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '브라질 내추럴, 콜롬비아 워시드, 에티오피아 내추럴, 과테말라 워시드',
        info_04_t: '다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_66',
        link: '/allCoffee/coffeeDetail',
        name: '백야 블렌드',
        taste01: '고소',
        taste02: '견과류',
        weight: '200',
        price: '13,000',
        cafeName: '오프사이트',
        logoImg: 'logo_16.png',
        productImg: 'pd_66.png',
        text_Info: '견과류의 맛과 크리미한 바디감이 특징으로 산미와 다른 맛들의 밸런스가 좋아서 부드럽게 드실 수 있습니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '에티오피아 워시드, 콜롬비아 워시드, 브라질 펄프드 내추럴',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_D_65',
        link: '/allCoffee/coffeeDetail',
        name: '브라질 세하도 디카프',
        taste01: '쌉쌀',
        taste02: '초콜릿',
        weight: '200',
        price: '19,000',
        cafeName: '오프사이트',
        logoImg: 'logo_16.png',
        productImg: 'pd_65.png',
        text_Info: '디카페인이지만 맛의 품질이 좋습니다. 브라우니, 초콜릿 파우더 같은 맛과 부드러운 바디감이 특징입니다.',
        info_00: '디카페인',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '산미가 없어요 ',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_64',
        link: '/allCoffee/coffeeDetail',
        name: '몬스테라',
        taste01: '과일',
        taste02: '깔끔한',
        weight: '250',
        price: '18,000',
        cafeName: '식물학 커피로스터스',
        logoImg: 'logo_15.png',
        productImg: 'pd_64.png',
        text_Info: '잘 익은 베리류의 풍미와 클린한 애프터를 느끼실 수 있는 시그니쳐 블렌드입니다.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목, 금 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '케냐 니에리 AA 혼합종 워시드, 에티오피아 예가체프 코케 G1 에얼룸 허니',
        info_04_t: '미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_63',
        link: '/allCoffee/coffeeDetail',
        name: '리들리',
        taste01: '견과류',
        taste02: '밸런스',
        weight: '250',
        price: '15,000',
        cafeName: '식물학 커피로스터스',
        logoImg: 'logo_15.png',
        productImg: 'pd_63.png',
        text_Info: '볶은 견과류의 고소한 맛과 기분좋은 바디감을 느끼실 수 있는 블렌드 입니다.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목, 금 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '브라질 세라도 NY2 FC 레드 카투아이 내추럴, 브라질 모지아나 NY2 FC 레드 카투아이 내추럴',
        info_04_t: '미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_62',
        link: '/allCoffee/coffeeDetail',
        name: '과테말라 팔렌시아 엘 소코로 풀리워시드',
        taste01: '달콤',
        taste02: '밸런스',
        weight: '250',
        price: '22,000',
        cafeName: '식물학 커피로스터스',
        logoImg: 'logo_15.png',
        productImg: 'pd_62.png',
        text_Info: '좋은 밸런스와 훌륭한 단맛을 느끼실수 있습니다.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목, 금 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_61',
        link: '/allCoffee/coffeeDetail',
        name: '마리모',
        taste01: '쌉쌀',
        taste02: '고소',
        weight: '200',
        price: '13,000',
        cafeName: '식물학 커피로스터스',
        logoImg: 'logo_15.png',
        productImg: 'pd_61.png',
        text_Info: '다크 초콜릿의 단맛과 풍부한 바디감을 느끼실 수 있는 블렌드 입니다.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목, 금 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '브라질 산토스 NY2 FC 레드 카투아이 내추럴, 인도 와야나 AA 로부스타 워시드',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_60',
        link: '/allCoffee/coffeeDetail',
        name: '나탈리',
        taste01: '쌉쌀',
        taste02: '고소',
        weight: '200',
        price: '16,000',
        cafeName: '영앤도터스',
        logoImg: 'logo_14.png',
        productImg: 'pd_60.png',
        text_Info: '잘 익은 딸기를 베어 문듯한 단맛과 적당한 산미의 조화를 이루는 와인의 풍미를 느낄 수 있어요.',
        info_00: '',
        info_01_t: '매주 월, 화, 수 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '가벼운 산미 ',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '파푸아뉴기니 바로이디아 콜브란, 엘살바도르 브라질 마르세예사, 코스타리카 로스 엔젤레스',
        info_04_t: '미디엄 로스팅  ',
        info_05_t: '공정 무역',
        info_05_p: '농부과 농장에게 공정한 가격으로 구입한 생두입니다.',
    },
    {
        id: 'product_B_59',
        link: '/allCoffee/coffeeDetail',
        name: '콜린',
        taste01: '달콤',
        taste02: '고소',
        weight: '200',
        price: '16,000',
        cafeName: '영앤도터스',
        logoImg: 'logo_14.png',
        productImg: 'pd_59.png',
        text_Info: '잘 익은 체리의 농후한 단맛과 고소한 아몬드 캐러멜이 입안 가득 남는 끝 맛을 느낄 수 있어요.',
        info_00: '',
        info_01_t: '매주 월, 화, 수 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '인도 바드라, 콜롬비아 나리노 베루코스, 코스타리카 로스 엔젤레스',
        info_04_t: '미디엄 다크 로스팅  ',
        info_05_t: '공정 무역',
        info_05_p: '농부과 농장에게 공정한 가격으로 구입한 생두입니다.',
    },
    {
        id: 'product_S_58',
        link: '/allCoffee/coffeeDetail',
        name: '에티오피아 예가체프 게르시',
        taste01: '달콤',
        taste02: '상큼',
        weight: '200',
        price: '22,000',
        cafeName: '영앤도터스',
        logoImg: 'logo_14.png',
        productImg: 'pd_58.png',
        text_Info: '입안 가득 꽃향기가 전해집니다. 꿀에 절여진 딸기처럼 달고, 깔끔함을 느낄 수 있어요.',
        info_00: '',
        info_01_t: '매주 월, 화, 수 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '라이트 미디엄 로스팅  ',
        info_05_t: '공정 무역',
        info_05_p: '농부과 농장에게 공정한 가격으로 구입한 생두입니다.',
    },
    {
        id: 'product_B_D_57',
        link: '/allCoffee/coffeeDetail',
        name: '센스 앤 센서빌리티',
        taste01: '달콤',
        taste02: '상큼',
        weight: '200',
        price: '18,000',
        cafeName: '영앤도터스',
        logoImg: 'logo_14.png',
        productImg: 'pd_57.png',
        text_Info: '감귤의 시트러스한 단맛을 바탕으로 시나몬과 고구마, 후미에는 꿀의 깊은 맛이 입 안에 남습니다.',
        info_00: '디카페인',
        info_01_t: '매주 월 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '가벼운 산미  ',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '멕시코 우아투스코 디카페인, 콜롬비아 엘 파라이소 디카페인',
        info_04_t: '미디엄 로스팅  ',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_56',
        link: '/allCoffee/coffeeDetail',
        name: '센스 앤 센서빌리티',
        taste01: '달콤',
        taste02: '깔끔한',
        weight: '200',
        price: '18,000',
        cafeName: '영앤도터스',
        logoImg: 'logo_14.png',
        productImg: 'pd_56.png',
        text_Info: '자스민의 향과 청사과의 달고 상큼함, 오렌지 시럽의 맛이 깔끔하고 쥬시한 커피입니다.',
        info_00: '',
        info_01_t: '매주 월 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '가벼운 산미  ',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '인도 마이소르 너겟 엑스트라 볼드 워시드, 에티오피아 리무 내추럴, 페루 초타 워시드',
        info_04_t: '라이트 미디엄 로스팅  ',
        info_05_t: '공정 무역',
        info_05_p: '농부과 농장에게 공정한 가격으로 구입한 생두입니다.',
    },
    {
        id: 'product_B_55',
        link: '/allCoffee/coffeeDetail',
        name: '센스 앤 센서빌리티',
        taste01: '밸런스',
        taste02: '부드러운',
        weight: '200',
        price: '12,000',
        cafeName: '커피 몽타주',
        logoImg: 'logo_13.png',
        productImg: 'pd_55.png',
        text_Info: '에스프레소의 풍부한 바디감과 쌉쌀하면서 달콤한 여운을 맛볼 수 있어요. 우유를 곁들여 마셨을 때 가장 맛있어요.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '인도 마이소르 너겟 엑스트라 볼드 워시드, 에티오피아 리무 내추럴, 페루 초타 워시드',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_54',
        link: '/allCoffee/coffeeDetail',
        name: '센스 앤 센서빌리티',
        taste01: '쌉쌀',
        taste02: '묵직한',
        weight: '200',
        price: '12,000',
        cafeName: '커피 몽타주',
        logoImg: 'logo_13.png',
        productImg: 'pd_54.png',
        text_Info: '높은 바디감을 느낄 수 있어요. 다크로스팅으로 볶아 묵직한 단맛을 원한다면 좋아하실 거예요.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '인도 마이소르 너겟 엑스트라 볼드 워시드, 에티오피아 리무 내추럴, 페루 초타 워시드',
        info_04_t: '다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_53',
        link: '/allCoffee/coffeeDetail',
        name: '센스 앤 센서빌리티',
        taste01: '깔끔한',
        taste02: '상큼',
        weight: '200',
        price: '15,000',
        cafeName: '커피 몽타주',
        logoImg: 'logo_13.png',
        productImg: 'pd_53.png',
        text_Info: '산미와 단맛이 조화로워요. 바디감이 부드럽고, 풍부한 향미와 산뜻한 여운을 느낄 수있어요.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '페루 미라도르 델 오소 워시드, 우간다 불라고 엘곤산 내추럴',
        info_04_t: '미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_52',
        link: '/allCoffee/coffeeDetail',
        name: '상큼한초밥',
        taste01: '고소',
        taste02: '상큼',
        weight: '200',
        price: '9,000',
        cafeName: '원더월 커피 로스터스',
        logoImg: 'logo_12.png',
        productImg: 'pd_52.png',
        text_Info: '호불호 강한 커피의 산미를 대중적으로 재해석한 커피로 고소함 속 상큼한 산미는 입맛을 돋우고 상쾌한 입가심을 선사합니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '브라질 모지아나 문도노보 옐로우 카투아이 내추럴, 에티오피아 테피 게이샤 G2 워시드',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_51',
        link: '/allCoffee/coffeeDetail',
        name: '에티오피아 리무 볼렌소',
        taste01: '초콜릿',
        taste02: '과일',
        weight: '250',
        price: '19,000',
        cafeName: '베르크 로스터스',
        logoImg: 'logo_11.png',
        productImg: 'pd_51.png',
        text_Info: '내추럴 프로세싱 특유의 건포도 향미가 선명히 느껴지며, 좋은 클린컵의 부드러운 산미는 오렌지의 향미로 느껴집니다. 부드러운 질감과 묵직한 초콜릿의 단맛이 긴 여운을 남기는 복합적인 향미와 단맛의 여운이 좋은 커피입니다.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목, 금 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_50',
        link: '/allCoffee/coffeeDetail',
        name: 'BABY BLEND',
        taste01: '묵직한',
        taste02: '풍부한',
        weight: '250',
        price: '16,000',
        cafeName: '베르크 로스터스',
        logoImg: 'logo_11.png',
        productImg: 'pd_50.png',
        text_Info: '부정적인 맛이 없이 처음부터 끝까지 마시기 편안합니다. 다크 초콜릿의 풍부한 단맛을 느낄 수 있고, 묵직한 바디감과 후미까지 길게 이어지는 진한 커피향을 경험해보세요.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목, 금 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '산미가 없어요 ',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '인도 카르나타카 아티칸 워시드, 온두라스 마리사벨 블렌드 카투아이 워시드',
        info_04_t: '다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_49',
        link: '/allCoffee/coffeeDetail',
        name: 'BABY BLEND',
        taste01: '깔끔한',
        taste02: '달콤',
        weight: '250',
        price: '16,000',
        cafeName: '베르크 로스터스',
        logoImg: 'logo_11.png',
        productImg: 'pd_49.png',
        text_Info: '탄맛이나 날카로운 신맛이 없이 처음부터 끝까지 먹기 편안하고 화려하지 않은 커피입니다. 고소한 브라운슈가, 캬라멜의 부드러운 질감과 풍부한 단맛을 느낄 수 있어요. 블랙커피와 밀크베리에이션을 동시에 고려했어요.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목, 금 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '에티오피아 리무 볼렌소 혼합종 내추럴, 인도 카르나타카 아티칸 워시드, 온두라스 마리사벨 블렌드 카투아이 워시드',
        info_04_t: '미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_D_48',
        link: '/allCoffee/coffeeDetail',
        name: 'Classic Blend',
        taste01: '고소',
        taste02: '부드러운',
        weight: '200',
        price: '15,000',
        cafeName: 'FELT',
        logoImg: 'logo_10.png',
        productImg: 'pd_48.png',
        text_Info: '흑설탕의 깊은 단맛, 견과류의 고소함, 은은한 산미가 균형을 이룬 부드럽고 풍부한 질감을 느낄 수 있습니다.',
        info_00: '디카페인',
        info_01_t: '매주 월, 화, 수, 목, 금 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '콜롬비아 산 아구스틴 디카페인, 과테말라 웨웨테낭고 디카페인, 에티오피아 사키소 테이드 디카페인 내추럴',
        info_04_t: '미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_47',
        link: '/allCoffee/coffeeDetail',
        name: 'Classic Blend',
        taste01: '쌉쌀',
        taste02: '묵직한',
        weight: '200',
        price: '13,000',
        cafeName: 'FELT',
        logoImg: 'logo_10.png',
        productImg: 'pd_47.png',
        text_Info: '다크 초콜릿의 풍미, 카카오닙스의 부드러운 쓴맛, 풍부한 질감을 느낄 수 있습니다.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목, 금 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '콜롬비아 안티오키아 라 수이자 카투라 워시드, 과테말라 산 로렌소 카투라 워시드, 코스타리카 Coopelibertad 카투라 워시드',
        info_04_t: '다크 로스팅',
        info_05_t: '직접 무역 ',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_B_46',
        link: '/allCoffee/coffeeDetail',
        name: 'Classic Blend',
        taste01: '밸런스',
        taste02: '깔끔한',
        weight: '200',
        price: '13,000',
        cafeName: 'FELT',
        logoImg: 'logo_10.png',
        productImg: 'pd_46.png',
        text_Info: '밀크 초콜릿의 단맛, 견과류의 고소함, 은은한 산미가 균형을 이룬 복합적인 향미를 지닌 블렌드입니다.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목, 금 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '콜롬비아 안티오키아 라 수이자 카투라 워시드, 과테말라 산 로렌소 카투라 워시드, 코스타리카 Coopelibertad 카투라 워시드',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '직접 무역 ',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_B_45',
        link: '/allCoffee/coffeeDetail',
        name: 'Seasonal Blend',
        taste01: '상큼',
        taste02: '깔끔한',
        weight: '200',
        price: '15,000',
        cafeName: 'FELT',
        logoImg: 'logo_10.png',
        productImg: 'pd_45.png',
        text_Info: '신선한 과일의 달콤함과 상큼함, 카라멜의 단맛이 조화를 이룬 실크처럼 부드러운 감촉의 계절 블렌드 입니다.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목, 금 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '콜롬비아 안티오키아 라 수이자 카투라 워시드, 과테말라 엘 사포테 카투라 세미 워시드, 에티오피아 구지 지게사 에얼룸 내추럴',
        info_04_t: '라이트 미디엄 로스팅 ',
        info_05_t: '직접 무역 ',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_B_44',
        link: '/allCoffee/coffeeDetail',
        name: '케냐 구아마 AA',
        taste01: '밸런스',
        taste02: '과일',
        weight: '200',
        price: '16,000',
        cafeName: '알렉스더커피',
        logoImg: 'logo_9.png',
        productImg: 'pd_44.png',
        text_Info: '은은한 향미와 최대한의 단맛이 끌어올려진 에티오피아 원두와 아몬드계열의 고소함,묵직한 바디,깨끗함을 느낄수 있는 과테말라 원두가 조화롭게 섞인 균형감 있는 커피입니다.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목, 금 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '에티오피아 구지 함벨라 부쿠 사이사, 과테말라 플로르 델 로사리오 워시드',
        info_04_t: '미디엄 로스팅 ',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_43',
        link: '/allCoffee/coffeeDetail',
        name: '케냐 구아마 AA',
        taste01: '상큼',
        taste02: '달콤',
        weight: '200',
        price: '16,000',
        cafeName: '알렉스더커피',
        logoImg: 'logo_9.png',
        productImg: 'pd_43.png',
        text_Info: '블랙베리와 체리톤의 향미와 적포도,조청 등의 단맛이 좋은 커피입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송 ',
        info_01_p: '',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '싱글 오리진  ',
        info_03_p: '',
        info_04_t: '미디엄 로스팅 ',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_42',
        link: '/allCoffee/coffeeDetail',
        name: '콜롬비아 엘 파라이소 리치',
        taste01: '과일',
        taste02: '달콤',
        weight: '200',
        price: '20,000',
        cafeName: '알렉스더커피',
        logoImg: 'logo_9.png',
        productImg: 'pd_42.png',
        text_Info: '열대과일과 리치의 향이 풍부합니다. 은은한 산미와 다양한 단맛들이 입을 즐겁게 하는 커피입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송 ',
        info_01_p: '',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '싱글 오리진  ',
        info_03_p: '',
        info_04_t: '라이트 로스팅 ',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_41',
        link: '/allCoffee/coffeeDetail',
        name: '인도 바드라 아라비카',
        taste01: '초콜릿',
        taste02: '묵직한',
        weight: '200',
        price: '15,000',
        cafeName: '알렉스더커피',
        logoImg: 'logo_9.png',
        productImg: 'pd_41.png',
        text_Info: '초콜릿의 달콤함과 호두의 고소함의 조화가 묵직한 바디감과 어우러져있는 매력적인 커피입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송 ',
        info_01_p: '',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '싱글 오리진  ',
        info_03_p: '',
        info_04_t: '라이트 미디엄 로스팅 ',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_40',
        link: '/allCoffee/coffeeDetail',
        name: '콜롬비아 타비 인디오 아나에로빅',
        taste01: '상큼',
        taste02: '깔끔한',
        weight: '200',
        price: '25,000',
        cafeName: '수수커피',
        logoImg: 'logo_8.jpg',
        productImg: 'pd_40.png',
        text_Info: '청포도의 산미와 단맛이 함께 느껴져요. 디저트가 필요한 오후에 드시면 좋을 커피입니다.',
        info_00: '',
        info_01_t: '매주 화 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '싱글 오리진  ',
        info_03_p: '',
        info_04_t: '라이트 미디엄 로스팅 ',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_39',
        link: '/allCoffee/coffeeDetail',
        name: '콜롬비아 타비 인디오 아나에로빅',
        taste01: '밸런스',
        taste02: '부드러운',
        weight: '200',
        price: '26,000',
        cafeName: '수수커피',
        logoImg: 'logo_8.jpg',
        productImg: 'pd_39.png',
        text_Info: '첫 모금의 파인애플의 단맛이 매력적입니다. 이후 따라오는 케인 슈가와 카카오닙스의 노트가 좋은 밸런스를 만들어 줍니다.',
        info_00: '',
        info_01_t: '매주 화 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '싱글 오리진  ',
        info_03_p: '',
        info_04_t: '미디엄 로스팅',
        info_05_t: '직접 무역',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_S_38',
        link: '/allCoffee/coffeeDetail',
        name: '에티오피아 시다모 두완초 G1 내추럴',
        taste01: '깔끔한',
        taste02: '달콤',
        weight: '200',
        price: '29,000',
        cafeName: '수수커피',
        logoImg: 'logo_8.jpg',
        productImg: 'pd_38.png',
        text_Info: '블루베리와 열대과일의 은은한 과일향과 클린한 애프터가 좋아요.',
        info_00: '',
        info_01_t: '매주 화 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '싱글 오리진  ',
        info_03_p: '',
        info_04_t: '미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_D_37',
        link: '/allCoffee/coffeeDetail',
        name: '수수블렌드',
        taste01: '밸런스',
        taste02: '달콤',
        weight: '200',
        price: '17,000',
        cafeName: '수수커피',
        logoImg: 'logo_8.jpg',
        productImg: 'pd_37.png',
        text_Info: '카라멜, 사과, 오렌지의 달콤함과 허브류의 여운이 좋은 디카페인 입니다.',
        info_00: '디카페인',
        info_01_t: '매주 화 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '싱글 오리진  ',
        info_03_p: '',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_36',
        link: '/allCoffee/coffeeDetail',
        name: '수수블렌드',
        taste01: '상큼',
        taste02: '깔끔한',
        weight: '200',
        price: '16,000',
        cafeName: '수수커피',
        logoImg: 'logo_8.jpg',
        productImg: 'pd_36.png',
        text_Info: '복숭아의 단맛과 산미가 깔끔하고 길게 이어집니다. 과일차처럼 부담 없이 마시기 좋습니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송  ',
        info_01_p: '',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '에티오피아 구지 우라가 고로 무다 내추럴, 에티오피아 예가체프 콩가 워시드',
        info_04_t: '미디엄 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_B_35',
        link: '/allCoffee/coffeeDetail',
        name: '노네임블렌드',
        taste01: '고소',
        taste02: '달콤',
        weight: '200',
        price: '15,000',
        cafeName: '수수커피',
        logoImg: 'logo_8.jpg',
        productImg: 'pd_35.png',
        text_Info: '견과류 고소함과 다크 초코의 단맛 밸런스가 좋고, 크림 음료들과도 잘 어우러져요.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송  ',
        info_01_p: '',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '콜롬비아 카우카 papayan 워시드, 브라질 미나스 제라이스 세하도 레드 카투아이 내추럴, 인도 만자라바드 하산 콜렉션 워시드',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '',
        info_05_p: '',
    },
    {
        id: 'product_S_34',
        link: '/allCoffee/coffeeDetail',
        name: '모카 돈 엘킨',
        taste01: '고소',
        taste02: '꽃향기',
        weight: '200',
        price: '32,000',
        cafeName: '수수커피',
        logoImg: 'logo_8.jpg',
        productImg: 'pd_34.png',
        text_Info: '마카다미아, 라즈베리, 장미, 티라이크 & 밀크초콜릿의 맛을 느낄 수 있는 커피입니다.',
        info_00: '',
        info_01_t: '매주 화 로스팅  ',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '라이트 미디엄 로스팅',
        info_05_t: '직접 무역 ',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_S_33',
        link: '/allCoffee/coffeeDetail',
        name: '모카 1959 CM',
        taste01: '과일',
        taste02: '달콤',
        weight: '200',
        price: '32,000',
        cafeName: '수수커피',
        logoImg: 'logo_8.jpg',
        productImg: 'pd_33.png',
        text_Info: '과일의 상큼함과 화이트 초콜릿의 단맛이 좋은 커피입니다.',
        info_00: '',
        info_01_t: '매주 화 로스팅  ',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '라이트 미디엄 로스팅',
        info_05_t: '직접 무역 ',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_B_32',
        link: '/allCoffee/coffeeDetail',
        name: '데일리뷰티 블렌드',
        taste01: '초콜릿',
        taste02: '달콤',
        weight: '200',
        price: '13,000',
        cafeName: '수수커피',
        logoImg: 'logo_8.jpg',
        productImg: 'pd_32.png',
        text_Info: '은은하게 퍼지는 산미와 초콜릿의 단맛이 느껴져요.',
        info_00: '',
        info_01_t: '매주 화 로스팅  ',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '콜롬비아 포파얀 내추럴, 에티오피아 콩가 워시드, 인도 핫산',
        info_04_t: '미디엄 로스팅',
        info_05_t: ' ',
        info_05_p: '',
    },
    {
        id: 'product_B_31',
        link: '/allCoffee/coffeeDetail',
        name: '77도 블렌드',
        taste01: '고소',
        taste02: '묵직한',
        weight: '200',
        price: '10,000',
        cafeName: '33도 커피로스터스',
        logoImg: 'logo_7.png',
        productImg: 'pd_31.png',
        text_Info: '다크 초콜릿 같은 맛과 함께 바디가 좋은 커피입니다.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목, 금 로스팅  ',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '과테말라, 브라질, 인도네시아',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: ' ',
        info_05_p: '',
    },
    {
        id: 'product_B_30',
        link: '/allCoffee/coffeeDetail',
        name: '66도 블렌드',
        taste01: '달콤',
        taste02: '부드러운',
        weight: '200',
        price: '14,000',
        cafeName: '33도 커피로스터스',
        logoImg: 'logo_7.png',
        productImg: 'pd_30.png',
        text_Info: '새콤달콤한 청포도 그리고 꿀 같은 단맛이 좋은 커피입니다.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목, 금 로스팅  ',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '에티오피아 내추럴, 에티오피아 허니',
        info_04_t: '라이트 미디엄 로스팅',
        info_05_t: ' ',
        info_05_p: '',
    },
    {
        id: 'product_B_29',
        link: '/allCoffee/coffeeDetail',
        name: '66도 블렌드',
        taste01: '깔끔한',
        taste02: '밸런스',
        weight: '200',
        price: '10,000',
        cafeName: '55도 커피로스터스',
        logoImg: 'logo_7.png',
        productImg: 'pd_28.png',
        text_Info: '초콜릿처럼 달콤하며, 밸런스가 좋은 커피입니다.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목, 금 로스팅  ',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요.',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '과테말라, 콜롬비아, 에티오피아',
        info_04_t: '미디엄 로스팅',
        info_05_t: ' ',
        info_05_p: '',
    },
    {
        id: 'product_S_29',
        link: '/allCoffee/coffeeDetail',
        name: '과테말라 엘 소코로 레드버번 풀리워시드',
        taste01: '달콤',
        taste02: '밸런스',
        weight: '200',
        price: '15,000',
        cafeName: '55도 커피로스터스',
        logoImg: 'logo_7.png',
        productImg: 'pd_28.png',
        text_Info: '은은한 과일의 부드러움과 갈색설탕의 단맛과 고소함의 밸런스가 좋은 커피입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '라이트 미디엄 로스팅',
        info_05_t: ' ',
        info_05_p: '',
    },
    {
        id: 'product_B_27',
        link: '/allCoffee/coffeeDetail',
        name: '44도 블렌드',
        taste01: '달콤',
        taste02: '밸런스',
        weight: '200',
        price: '9,000',
        cafeName: '55도 커피로스터스',
        logoImg: 'logo_7.png',
        productImg: 'pd_27.png',
        text_Info: '바디감과 달콤함이 적절한 밸런스에 초점을 두며, 초콜릿티와 호두같은 고소함이 매력적인 블렌드입니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '브라질 내추럴, 콜롬비아 워시드, 과테말라 워시드, 에티오피아 예가체프 워시드',
        info_04_t: '다크 로스팅',
        info_05_t: ' ',
        info_05_p: '',
    },
    {
        id: 'product_B_D_26',
        link: '/allCoffee/coffeeDetail',
        name: '카라멜 슬럽',
        taste01: '상큼',
        taste02: '깔끔한',
        weight: '200',
        price: '11,500',
        cafeName: '하늘에커피',
        logoImg: 'logo_6.png',
        productImg: 'pd_26.png',
        text_Info: '케냐 AA를 베이스로 에티오피아 모모라 내추럴을 더하였습니다. 오렌지의 산미와 카라멜의 단맛, 은은하게 퍼지는 꽃향의 여운을 느끼실 수 있습니다.',
        info_00: '디카페인',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '케냐 AA Plus 키리냐가 워시드, 에티오피아 구지 모모라 AQ2 내추럴',
        info_04_t: '라이트 미디엄 로스팅',
        info_05_t: ' ',
        info_05_p: '',
    },
    {
        id: 'product_S_D_25',
        link: '/allCoffee/coffeeDetail',
        name: '카라멜 슬럽',
        taste01: '밸런스',
        taste02: '견과류',
        weight: '200',
        price: '11,000',
        cafeName: '하늘에커피',
        logoImg: 'logo_6.png',
        productImg: 'pd_25.png',
        text_Info: '산뜻한 건과일 플레이버 뒤로 이어지는 토피넛과 코코아의 달콤함으로, 안정된 밸런스를 가진 디카페인 커피입니다.',
        info_00: '디카페인',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: ' ',
        info_05_p: '',
    },
    {
        id: 'product_B_24',
        link: '/allCoffee/coffeeDetail',
        name: '카라멜 슬럽',
        taste01: '고소',
        taste02: '부드러운',
        weight: '250',
        price: '13,000',
        cafeName: '슬러핀 커피',
        logoImg: 'logo_5.jpg',
        productImg: 'pd_24.png',
        text_Info: '달콤한 밀크초콜릿이 연상되는 블렌드입니다. 카페라떼에 잘 어울리며 아메리카노도 달콤합니다.',
        info_00: '',
        info_01_t: '3일 내 볶은 원두만 배송',
        info_01_p: '',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '',
        info_04_t: '미디엄 로스팅',
        info_05_t: ' ',
        info_05_p: '',
    },
    {
        id: 'product_S_23',
        link: '/allCoffee/coffeeDetail',
        name: '케냐 기티투 AB',
        taste01: '과일',
        taste02: '부드러운',
        weight: '150',
        price: '13,000',
        cafeName: '.txt',
        logoImg: 'logo_4.png',
        productImg: 'pd_23.png',
        text_Info: '딸기 주스와 사과의 향미, 밀크 초콜릿의 단맛이 부드럽게 느껴집니다.',
        info_00: '',
        info_01_t: '매주 월 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요 ',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '라이트 미디엄 로스팅',
        info_05_t: ' ',
        info_05_p: '',
    },
    {
        id: 'product_S_22',
        link: '/allCoffee/coffeeDetail',
        name: '케냐 기티투 AB',
        taste01: '과일',
        taste02: '달콤',
        weight: '150',
        price: '15,000',
        cafeName: '.txt',
        logoImg: 'logo_4.png',
        productImg: 'pd_22.png',
        text_Info: '자몽, 건포도의 산미와 꿀 늬앙스의 단맛이 훌륭합니다.',
        info_00: '',
        info_01_t: '매주 월 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요 ',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '라이트 미디엄 로스팅',
        info_05_t: ' ',
        info_05_p: '',
    },
    {
        id: 'product_S_21',
        link: '/allCoffee/coffeeDetail',
        name: '엘 카미노',
        taste01: '달콤',
        taste02: '깔끔한',
        weight: '150',
        price: '25,000',
        cafeName: '.txt',
        logoImg: 'logo_4.png',
        productImg: 'pd_21.png',
        text_Info: '오렌지와 말린 자두의 산미와 대추 야자의 단맛이 깔끔하게 어우러집니다.',
        info_00: '',
        info_01_t: '매주 월 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요 ',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '라이트 미디엄 로스팅',
        info_05_t: ' ',
        info_05_p: '',
    },
    {
        id: 'product_B_20',
        link: '/allCoffee/coffeeDetail',
        name: '엘 카미노',
        taste01: '고소',
        taste02: '견과류',
        weight: '200',
        price: '14,000',
        cafeName: '피어 커피로스터스',
        logoImg: 'logo_3.png',
        productImg: 'pd_20.png',
        text_Info: '고소하고, 묵직하지만, 단맛이 잘 느껴져요. 마실 때 이물감이 없이 클린컵도 좋은 커피입니다.',
        info_00: '',
        info_01_t: '매주 월, 화, 수, 목 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요 ',
        info_02_t: '산미가 없어요',
        info_02_p: '신 맛이 없어서 고소해요.',
        info_03_t: '블렌드',
        info_03_p: '과테말라 엘소코로 산로렌조 풀리워시드 레드 카투라, 콜롬비아 후일라 레드 카투라 수프리모 풀리워시드, 브라질 산타이네스 옐로우 버본 펄프드 내추럴',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: ' ',
        info_05_p: '',
    },
    {
        id: 'product_B_19',
        link: '/allCoffee/coffeeDetail',
        name: '피어투피어',
        taste01: '과일',
        taste02: '밸런스',
        weight: '200',
        price: '17,000',
        cafeName: '피어 커피로스터스',
        logoImg: 'logo_3.png',
        productImg: 'pd_19.png',
        text_Info: '은은한 시트러스, 핵과류의 산미와 부드러운 단맛이 좋으며, 티처럼 편하게 즐기기 좋은 커피입니다.',
        info_00: '',
        info_01_t: '매주 화 로스팅',
        info_01_p: '출고일 기준 3일 내 볶은 원두만 배송해요 ',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '에티오피아 첼베사 워시드, 코스타리카 헤네시스 비야사치 워시드, 케냐 띠리쿠 AB 워시드, 과테말라 인헤르토 네이티보 블렌드 워시드',
        info_04_t: '미디엄 로스팅',
        info_05_t: ' ',
        info_05_p: '',
    },
    {
        id: 'product_S_D_18',
        link: '/allCoffee/coffeeDetail',
        name: '콜롬비아 디카페인',
        taste01: '밸런스',
        taste02: '초콜릿',
        weight: '200',
        price: '15,000',
        cafeName: '피어 커피로스터스',
        logoImg: 'logo_3.png',
        productImg: 'pd_18.png',
        text_Info: '초콜릿티한 달콤함과 좋은 단맛으로 누구나 마시기 편한 커피입니다.',
        info_00: '디카페인',
        info_01: '3일 내 볶은 원두만 배송 ',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '다크 로스팅',
        info_05_t: ' ',
        info_05_p: '',
    },
    {
        id: 'product_B_17',
        link: '/allCoffee/coffeeDetail',
        name: '메이데이',
        taste01: '상큼',
        taste02: '깔끔한',
        weight: '210',
        price: '15,000',
        cafeName: '센터 커피',
        logoImg: 'logo_2.png',
        productImg: 'pd_17.png',
        text_Info: '시럽 같은 바디감과 카라멜의 단맛이 느껴지며, 식을수록 바디감에서 복합적인 과일 맛이 느껴져요.',
        info_00: '',
        info_01: '3일 내 볶은 원두만 배송 ',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '에티오피아 시다모 벤사 사가라 에얼룸 내추럴, 콜롬비아 퀸디오 라 디비사 펑크 버본 워시드, 과테말라 프라이하네스 버본 워시드',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: ' ',
        info_05_p: '',
    },
    {
        id: 'product_S_D_16',
        link: '/allCoffee/coffeeDetail',
        name: '디카페인 에티오피아 예가체프 워카 내추럴 스위스 워터',
        taste01: '고소',
        taste02: '묵직한',
        weight: '210',
        price: '13,000',
        cafeName: '센터 커피',
        logoImg: 'logo_2.png',
        productImg: 'pd_16.png',
        text_Info: '캐러멜의 단맛이 느껴지고, 식을수록 건자두의 플레이버가 입안은 채워줍니다. 다크초콜릿의 플레이버가 전체적인 밸런스를 잡아주는 커피입니다.',
        info_00: '디카페인',
        info_01: '3일 내 볶은 원두만 배송 ',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '싱글오리진',
        info_03_p: '',
        info_04_t: '다크 로스팅',
        info_05_t: ' ',
        info_05_p: '',
    },
    {
        id: 'product_S_15',
        link: '/allCoffee/coffeeDetail',
        name: '에티오피아 구지 우라가 테베 부르카 워시드',
        taste01: '상큼',
        taste02: '깔끔한',
        weight: '210',
        price: '18,000',
        cafeName: '센터 커피',
        logoImg: 'logo_2.png',
        productImg: 'pd_15.png',
        text_Info: '오렌지 같은 상큼함, 꿀 같은 단맛이 느껴지며, 복숭아의 플레이버가 은은하게 입안에 퍼집니다.',
        info_01: '3일 내 볶은 원두만 배송 ',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '싱글오리진',
        info_03_p: '',
        info_04_t: '라이트 로스팅',
        info_05_t: ' ',
        info_05_p: '',
    },
    {
        id: 'product_S_14',
        link: '/allCoffee/coffeeDetail',
        name: '콜롬비아 우일라 비야 플로 핑크 버번 내추럴 ASD',
        taste01: '달콤',
        taste02: '묵직한',
        weight: '210',
        price: '20,000',
        cafeName: '센터 커피',
        logoImg: 'logo_2.png',
        productImg: 'pd_14.png',
        text_Info: '패션 프룻의 아로마가 강렬합니다. 자두 청의 단맛과 레드 와인 같은 플레이버가 다채로운 커피입니다.',
        info_01: '3일 내 볶은 원두만 배송 ',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '싱글오리진',
        info_03_p: '',
        info_04_t: '라이트 로스팅',
        info_05_t: ' ',
        info_05_p: '',
    },
    {
        id: 'product_B_13',
        link: '/allCoffee/coffeeDetail',
        name: '위WE',
        taste01: '달콤',
        taste02: '부드러운',
        weight: '200',
        price: '14,000',
        cafeName: '나무사이로',
        logoImg: 'logo_1.png',
        productImg: 'pd_13.png',
        text_Info: '바닐라의 달콤함과 복숭아의 향긋함 그리고 부드러운 감촉이 인상적인 커피입니다.',
        info_01: '3일 내 볶은 원두만 배송 ',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '과테말라 웨웨테낭고 풀리 워시드, 에티오피아 워르카 워시드',
        info_04_t: '미디엄 로스팅',
        info_05_t: '직접 무역 ',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_B_12',
        link: '/allCoffee/coffeeDetail',
        name: '숲',
        taste01: '밸런스',
        taste02: '과일',
        weight: '200',
        price: '13,500',
        cafeName: '나무사이로',
        logoImg: 'logo_1.png',
        productImg: 'pd_12.png',
        text_Info: '달고나의 달콤 쌉싸름한 맛, 그리고 레몬, 민트의 싱그러운 느낌이 조화를 이룹니다.',
        info_01: '3일 내 볶은 원두만 배송 ',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '에티오피아 워르카 워시드, 브라질 카르모 내추럴',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '직접 무역 ',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_B_11',
        link: '/allCoffee/coffeeDetail',
        name: '다크우드',
        taste01: '달콤',
        taste02: '과일',
        weight: '200',
        price: '13,500',
        cafeName: '나무사이로',
        logoImg: 'logo_1.png',
        productImg: 'pd_11.png',
        text_Info: '묵직하면서도 매끄럽고 오랫동안 입안을 맴도는 여운이 있는 커피입니다. 농밀한 단맛이 특징입니다.',
        info_01: '3일 내 볶은 원두만 배송 ',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '과테말라 웨웨테낭고 와이칸 워시드, 에티오피아 이디도 비르투칸 부투 혼합종 내추럴',
        info_04_t: '다크 로스팅',
        info_05_t: '직접 무역 ',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_B_10',
        link: '/allCoffee/coffeeDetail',
        name: '풍요로운 땅',
        taste01: '쌉쌀',
        taste02: '깔끔한',
        weight: '200',
        price: '12,500',
        cafeName: '나무사이로',
        logoImg: 'logo_1.png',
        productImg: 'pd_10.png',
        text_Info: '누구나 편안히 마실 수 있는 커피로, 달콤쌉싸름하고 입 안 마무리는 시원함을 느낄 수 있어요.',
        info_01: '3일 내 볶은 원두만 배송 ',
        info_02_t: '가벼운 산미',
        info_02_p: '신 맛이 가볍게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '페루 카하마르카 산이그나시오 워시드, 브라질 카르모 세하네그라 내추럴, 콜롬비아 나리노 워시드',
        info_04_t: '다크 로스팅',
        info_05_t: '직접 무역 ',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_09',
        link: '/allCoffee/coffeeDetail',
        name: '디카프리오',
        taste01: '쌉쌀',
        taste02: '깔끔한',
        weight: '200',
        price: '15,000',
        cafeName: '나무사이로',
        logoImg: 'logo_1.png',
        productImg: 'pd_9.png',
        text_Info: '바닐라, 건과일, 견과류, 크림 브륄레, 누룽지 사탕 등의 향미가 두드러집니다. 매일 먹어도 질리지 않는 마치 밥같은 커피로 누가 마셔도 좋습니다.',
        info_01: '3일 내 볶은 원두만 배송 ',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '직접 무역 ',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_08',
        link: '/allCoffee/coffeeDetail',
        name: '브릴리',
        taste01: '고소',
        taste02: '부드러운',
        weight: '200',
        price: '12,500',
        cafeName: '나무사이로',
        logoImg: 'logo_1.png',
        productImg: 'pd_8.png',
        text_Info: '바닐라, 건과일, 견과류, 크림 브륄레, 누룽지 사탕 등의 향미가 두드러집니다. 매일 먹어도 질리지 않는 마치 밥같은 커피로 누가 마셔도 좋습니다.',
        info_01: '3일 내 볶은 원두만 배송 ',
        info_02_t: '약한 산미',
        info_02_p: '신 맛이 약하게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '직접 무역 ',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_07',
        link: '/allCoffee/coffeeDetail',
        name: '봄의 제전',
        taste01: '달콤',
        taste02: '과일',
        weight: '200',
        price: '17,000',
        cafeName: '나무사이로',
        logoImg: 'logo_1.png',
        productImg: 'pd_7.png',
        text_Info: '꽃향기도 느껴지고, 섬세하고도 달콤한 생기가 느껴지는 커피입니다. 새콤달콤하고 활기가 넘치는 신맛과 잼 같은 풍부하고 끈적하지만 탄력성 있는 촉감을 경험할 수 있습니다.',
        info_01: '3일 내 볶은 원두만 배송 ',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '라이트 미디엄 로스팅',
        info_05_t: '직접 무역 ',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_06',
        link: '/allCoffee/coffeeDetail',
        name: '날아올라',
        taste01: '꽃향기',
        taste02: '화사한',
        weight: '200',
        price: '15,000',
        cafeName: '나무사이로',
        logoImg: 'logo_1.png',
        productImg: 'pd_6.png',
        text_Info: '단 맛이 특징이며, 자스민 향을 느낄 수 있습니다.',
        info_01: '3일 내 볶은 원두만 배송 ',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '라이트 미디엄 로스팅',
        info_05_t: '직접 무역 ',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_05',
        link: '/allCoffee/coffeeDetail',
        name: '와이칸 다크',
        taste01: '초콜릿',
        taste02: '고소',
        weight: '200',
        price: '13,000',
        cafeName: '나무사이로',
        logoImg: 'logo_1.png',
        productImg: 'pd_5.png',
        text_Info: '다크초콜릿, 블랙체리, 솔티드카라멜의 쌉쌀하고 단 맛이 일품이며 뒷 여운이 깔끔해요.',
        info_01: '3일 내 볶은 원두만 배송 ',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '다크 로스팅',
        info_05_t: '직접 무역 ',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_04',
        link: '/allCoffee/coffeeDetail',
        name: '몽상스',
        taste01: '밸런스',
        taste02: '달콤',
        weight: '200',
        price: '18,000',
        cafeName: '나무사이로',
        logoImg: 'logo_1.png',
        productImg: 'pd_4.png',
        text_Info: '목넘김이 매끄러워 술술 넘어가는, 달고 부드럽고 바디가 좋은 케냐 커피입니다. 특히 라떼로 맛있습니다.',
        info_01: '3일 내 볶은 원두만 배송 ',
        info_02_t: '새콤한 산미',
        info_02_p: '신 맛이 잘 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '미디엄 다크 로스팅',
        info_05_t: '직접 무역 ',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_03',
        link: '/allCoffee/coffeeDetail',
        name: '스트로베리',
        taste01: '과일',
        taste02: '달콤',
        weight: '200',
        price: '36,000',
        cafeName: '나무사이로',
        logoImg: 'logo_1.png',
        productImg: 'pd_3.png',
        text_Info: '딸기쉐이크, 달콤한 초콜릿, 꽃향기가 기분 좋아요.',
        info_01: '3일 내 볶은 원두만 배송 ',
        info_02_t: '강한 산미',
        info_02_p: '신 맛이 강하게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '미디엄 로스팅',
        info_05_t: '직접 무역 ',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_02',
        link: '/allCoffee/coffeeDetail',
        name: '그레이프',
        taste01: '꽃향기',
        taste02: '달콤',
        weight: '200',
        price: '36,000',
        cafeName: '나무사이로',
        logoImg: 'logo_1.png',
        productImg: 'pd_2.png',
        text_Info: '포도의 향기와 맛을 듬뿍 느껴보세요.',
        info_01: '3일 내 볶은 원두만 배송 ',
        info_02_t: '강한 산미',
        info_02_p: '신 맛이 강하게 느껴져요.',
        info_03_t: '싱글 오리진',
        info_03_p: '',
        info_04_t: '미디엄 로스팅',
        info_05_t: '직접 무역 ',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    },
    {
        id: 'product_01',
        link: '/allCoffee/coffeeDetail',
        name: '나비',
        taste01: '꽃향기',
        taste02: '과일',
        weight: '200',
        price: '23,000',
        cafeName: '나무사이로',
        logoImg: 'logo_1.png',
        productImg: 'pd_1.png',
        cafe_poto_01: 'poto_1_1.jpg',
        cafe_poto_02: 'poto_1_2.jpg',
        cafe_poto_03: 'poto_1_3.jpg',
        text_Info: '깨끗하고 깔끔하며 오렌지 주스를 마시는 것 같은 커피입니다.',
        info_01: '3일 내 볶은 원두만 배송 ',
        info_02_t: '강한 산미',
        info_02_p: '신 맛이 강하게 느껴져요.',
        info_03_t: '블렌드',
        info_03_p: '에티오피아 이디도 비르투칸 부투 혼합종 내추럴, 콜롬비아 아르메니아 비야라소 핑크버본 워시드 무산소 발효',
        info_04_t: '미디엄 로스팅',
        info_05_t: '직접 무역 ',
        info_05_p: '현지 농장과 지속 가능한 관계를 맺으며 공정한 가격으로 직접 거래하는 로스터리입니다.',
    }
]

export default all_product