const all_rostery = [
    {
        id: 'cafe01',
        link: '/allRostery/rosteryDetail_01',
        cafeName: '나무사이로',
        logoImg: 'logo_1.png',
        cafe_poto_01: 'poto_1_1.jpg',
        cafe_poto_02: 'poto_1_2.jpg',
        cafe_poto_03: 'poto_1_3.jpg',
        about: '2002년에 시작한 나무사이로는\n 한 잔의 커피로 우리의 일상이 풍요로워지기를 바랍니다. 지속적으로 산지를 방문하여 농부•생산업자와 소통하며 좋은 재료와 논리적인 로스팅, 철저한 품질관리를 기반으로 커피가 가진 다양한 매력을 소개합니다.',
        rocation: '경기도 성남시 분당구 석운로 33, 나무사이로',
        sns: 'Instagram',
        sns_p: 'namusairocoffee'
    },
    {
        id: 'cafe02',
        link: '/allRostery/rosteryDetail',
        cafeName: '센터커피',
        logoImg: 'logo_2.png',
        cafe_poto_01: 'poto_2_1.jpg',
        cafe_poto_02: 'poto_2_2.jpg',
        cafe_poto_03: 'poto_2_3.jpg',
        about: '센터커피는 최고의 커피를 찾아 여러분들께 소개해드려, 커피를 통해 ‘일상 작은 사치‘를 느끼실 수 있게 만들어진 커피 브랜드입니다. 몸에 편하고 좋은 커피는 어떤 커피인지 어떤 곳에서 어떤 농부가 만드는지, 어떻게 재배되는지, 어떻게 로스팅이 되는지 좋은 재료부터 가장 최고로 맛을 내기 위한 열정과 과정을 이야기하고자 합니다.',
        rocation: '서울특별시 성동구 서울숲 2길 28-11',
        sns: 'Instagram',
        sns_p: 'centercoffee'
    },
    {
        id: 'cafe03',
        link: '/allRostery/rosteryDetail',
        cafeName: '피어 커피로스터스',
        logoImg: 'logo_3.png',
        cafe_poto_01: 'poto_3_1.jpg',
        cafe_poto_02: 'poto_3_2.jpg',
        cafe_poto_03: 'poto_3_3.jpg',
        about: '친구처럼 익숙한 커피 브랜드 PEER ;또래, 친구  <br/><br/>로스팅 팩토리에서는 철저한 생두 관리와 Quality Control을 책임지고 있지만, 매장에서는 고객들에게 쉽고 편안하게 다가가기 위해 많은 노력을 기울이고 있습니다.  <br/><br/>피어 커피로스터스가 로스팅할 때 가장 중요하게 생각하는 부분은 *단맛*과 *클린컵*입니다. 단맛과 클린컵이 뛰어난 커피는 한 잔을 더 마셔도 부담스럽지 않으며 피어커피로스터스가 지향하는 *편안하게 즐기는 스페셜티 커피*라는 목표에 다가갈 수 있는 방법이라고 생각하고 있습니다.',
        rocation: '서울특별시 중구 청구로 123',
        sns: 'Instagram',
        sns_p: 'peer_coffee_roasters'
    },
    {
        id: 'cafe04',
        link: '/allRostery/rosteryDetail',
        cafeName: '.txt',
        logoImg: 'logo_4.png',
        cafe_poto_01: 'poto_4_1.jpg',
        cafe_poto_02: 'poto_4_2.jpg',
        cafe_poto_03: 'poto_4_3.jpg',
        about: '간단하게, 명료하게, 정확하게.<br/><br/>간단하고 명료하며 정확하기 위해 노력합니다.<br/><br/>매일 가볍게 즐길 수 있는 쉽고 편안한 커피를 지향합니다.',
        rocation: '서울특별시 종로구 창덕궁길 121',
        sns: 'Instagram',
        sns_p: 'txtcoffee'
    },
    {
        id: 'cafe05',
        link: '/allRostery/rosteryDetail',
        cafeName: '슬러핀커피',
        logoImg: 'logo_5.jpeg',
        cafe_poto_01: 'poto_5_1.jpg',
        cafe_poto_02: 'poto_5_2.jpg',
        cafe_poto_03: 'poto_5_3.jpg',
        about: '호로록, 슬러핀커피입니다. 맛있는 커피는 생두 고르는 것 부터 시작합니다.<br/><br/>Q-Grader, R-Grader가 제철 커피를 잘 고르고 로스팅까지 정성 껏 진행합니다.<br/><br/>우리들의 일이자 휴식인 커피, 오늘도 즐커하세요.',
        rocation: '광주 동구 준법로 14 1층 슬러핀커피 로스터스',
        sns: 'Instagram',
        sns_p: 'slurpin.coffee'
    },
    {
        id: 'cafe06',
        link: '/allRostery/rosteryDetail',
        cafeName: '하늘에커피',
        logoImg: 'logo_6.png',
        cafe_poto_01: 'poto_6_1.jpg',
        cafe_poto_02: 'poto_6_2.jpg',
        cafe_poto_03: 'poto_6_3.jpg',
        about: '원두만큼은 걱정 안하시도록, 제대로 *에스코트*하겠습니다.<br/><br/>손님들로부터 "커피 맛있다."는 말씀, 꼭 듣게 해드리겠습니다.<br/><br/>능숙한 커피전문가가 되실 때까지, 뒤에서 힘껏 조력하겠습니다.',
        rocation: '제주시 애월읍 고내3길 14(애월공장) <br/>서울시 마포구 독막로32길 6(신수공장)',
        sns: 'Instagram',
        sns_p: 'haneulae_coffee'
    },
    {
        id: 'cafe07',
        link: '/allRostery/rosteryDetail',
        cafeName: '55도 커피로스터스',
        logoImg: 'logo_7.png',
        cafe_poto_01: 'poto_7_1.jpg',
        cafe_poto_02: 'poto_7_2.jpg',
        cafe_poto_03: 'poto_7_3.jpg',
        about: '*커피에 색을 입히다* <br/><br/>Good Temperature for latte , 팔레트에 다양한 색을 조합하여 화판에 작품을 그리듯이 저희 회사는 *커피에 색을 입히다.* 라는 주제로 각 매장의 컨셉에 맞는 원두를 컨설팅하고 있는 로스팅 전문 회사입니다. <br/><br/>최고 품질의 커피를 제공하기 위해 좋은 생두와 시설을 갖추어 철저한 품질 평가를 하고 있습니다. 항상 더 좋은 커피, 더 좋은 환경,더 좋은 관계를 만들어 사회에 좋은 영향을 끼칠 수 있는 회사로 성장하기 위해 노력하고 있습니다.',
        rocation: '경기도 성남시 분당구 안골로 60 (서현동) 1층',
        sns: 'Instagram',
        sns_p: '55do_official'
    },
    {
        id: 'cafe08',
        link: '/allRostery/rosteryDetail',
        cafeName: '수수커피',
        logoImg: 'logo_8.jpg',
        cafe_poto_01: 'poto_8_1.jpg',
        cafe_poto_02: 'poto_8_2.jpg',
        cafe_poto_03: 'poto_8_3.jpg',
        about: '수수커피는 *수수하다*라는 사전적 의미처럼 꾸미지 않고 커피가 가진 본연의 맛을 추구합니다. <br/><br/>생두가 한 잔의 커피가 되기까지 여정의 마무리는 결국 *마시는 사람*입니다. 커피를 내려 마실 때 그 원두가 가진 스토리를 알고 있는지, 어떤 페어링을 하는지, 어떤 부분에서 어떤 노트를 찾는지에 따라 한 잔에 대한 감각은 달라질 수 있습니다. <br/><br/>저희는 마시는 사람에게 아직은 낯선 원두에 설레는 호기심을 불어 넣고, 취향으로서의 커피를 즐길 수 있게 돕고자 합니다.',
        rocation: '서울시 강남구 강남대로154길 24 준영빌딩 1층',
        sns: 'Instagram',
        sns_p: 'soosoocoffee'
    },
    {
        id: 'cafe09',
        link: '/allRostery/rosteryDetail',
        cafeName: '알렉스더커피',
        logoImg: 'logo_9.png',
        cafe_poto_01: 'poto_9_1.jpg',
        cafe_poto_02: 'poto_9_2.jpg',
        cafe_poto_03: 'poto_9_3.jpg',
        about: '알렉스더커피는 커피를 합니다. <br/>좋은 커피, 그 자체가 가진 진정성과 매력을 이야기하고 실천합니다. <br/><br/>좋은 커피를 찾고 또 그와 만나 소통하고, 만들고, 그것을 좋은 사람들과 나누며 이를 통하여 우리들의 일상에 행복과 풍요로움을 더하는 것이 알렉스더커피가 추구하고 나아갈 방향입니다. <br/><br/>we do coffee',
        rocation: '경기 용인시 처인구 백암면 삼백로835번길 12',
        sns: 'Instagram',
        sns_p: 'alexthecoffee'
    },
    {
        id: 'cafe10',
        link: '/allRostery/rosteryDetail',
        cafeName: 'FELT',
        logoImg: 'logo_10.png',
        cafe_poto_01: 'poto_10_1.jpg',
        cafe_poto_02: 'poto_10_2.jpg',
        cafe_poto_03: 'poto_10_3.jpg',
        about: '매년 커피 산지를 방문합니다. 산지 방문을 통해 생두를 선별하고 전문 로스터와 바리스타의 손을 거쳐, 손님에게 한 잔의 커피를 건네는 순간까지 보다 훌륭하고 일정한 품질을 위해 노력합니다. <br/><br/> 2015년 쇼룸 오픈을 시작으로 광화문 D타워, 도산공원 지점을 오픈하였고 이에 따라 로스터리도 함께 확장하고 있습니다.',
        rocation: '서울시 마포구 서강로 11길 23',
        sns: 'Instagram',
        sns_p: 'felt_seoul'
    },
    {
        id: 'cafe11',
        link: '/allRostery/rosteryDetail',
        cafeName: '베르크 로스터스',
        logoImg: 'logo_11.png',
        cafe_poto_01: 'poto_11_1.jpg',
        cafe_poto_02: 'poto_11_2.jpg',
        cafe_poto_03: 'poto_11_3.jpg',
        about: '부산에 위치한 스몰배치 스페셜티 커피 로스터리이자, 서로 다른 경험과 개성을 가진 4명이 모여 긍정적인 삶의 변화를 추구하는 회사 입니다. <br/><br/>각자의 위치에서 역할에 따라 다양한 활동을 하고 있으며 모든 구성원들이 즐겁게 열정을 유지하며 늘 새로운 방식으로 변화하는 매력적인 브랜드가 되고자 합니다. <br/><br/>커피를 만드는 저희와, 저희 커피를 사용하시는 분, 그리고 커피를 드시는 분까지 좋은 관계를 만들고 함께 하는 것에 의미를 두고 발전하는 것을 중요하게 생각합니다.',
        rocation: '부산 부산진구 전포동 356-6 지하1층',
        sns: 'Instagram',
        sns_p: 'werk.roasters'
    },
    {
        id: 'cafe12',
        link: '/allRostery/rosteryDetail',
        cafeName: '원더월 커피 로스터스',
        logoImg: 'logo_12.png',
        cafe_poto_01: 'poto_12_1.jpg',
        cafe_poto_02: 'poto_12_2.jpg',
        cafe_poto_03: 'poto_12_3.jpg',
        about: '원더월 커피 로스터스 wonderwall coffee roasters <br/><br/>‘커피를 즐겁게 그리고 함께’ <br/><br/>원더월은 일방적인 로스터의 생각이 나 공감되지 않는 커피의 개성에만 집중하는 것이 아닌 모든 사람들이 좋아하고 누구나 쉽게 마실 수 있으며 커피를 학문, 기호식품을 넘어서 하나의 대중문화로 받아들이는 궁극의 대중성을 추구합니다.',
        rocation: '서울 동대문구 답십리로 80 1층',
        sns: 'Instagram',
        sns_p: 'kimguitar_'
    },
    {
        id: 'cafe13',
        link: '/allRostery/rosteryDetail',
        cafeName: '커피몽타주',
        logoImg: 'logo_13.png',
        cafe_poto_01: 'poto_13_1.jpg',
        cafe_poto_02: 'poto_13_2.jpg',
        cafe_poto_03: 'poto_13_3.jpg',
        about: '"영화 같은 일상, 그 일상 속의 커피 한 잔" <br/>한 편의 영화처럼 커피를 둘러싼 사람과 일상 모두를 몽타주(Montage, 편집) 할 수 있기를... <br/><br/>안정적인 로스팅 품질 관리로 잘 알려진 커피몽타주는 전국 150여 곳의 크고 작은 카페에 커피를 납품하고 있으며, 고품질의 생두 구매를 위하여 각종 해외 커피 옥션 참여 및 산지 직거래를 시도하고 있습니다. 좋은 생두를 찾기 위한 노력, 더 나은 로스팅을 위한 매일의 시도, 최선의 커피 추출을 위한 고민들. 맛있는 커피 한 잔에 정직한 과정을 담기 위해 우리는 오늘도 고민합니다.',
        rocation: '서울 강동구 올림픽로48길 23-12 1층',
        sns: 'Instagram',
        sns_p: 'coffeemontage'
    },
    {
        id: 'cafe14',
        link: '/allRostery/rosteryDetail',
        cafeName: '영앤도터스',
        logoImg: 'logo_14.png',
        cafe_poto_01: 'poto_14_1.jpg',
        cafe_poto_02: 'poto_14_2.jpg',
        cafe_poto_03: 'poto_14_3.jpg',
        about: 'Coffee is Complex! <br/><br/>영앤도터스는 커피가 가진 다양한 매력을 선보이기 위해, <br/>좋은 생두를 선별하고, 일관성 있고 논리적인 로스팅을 거쳐<br/>맛있는 한 잔의 커피로 고객의 손의 쥐어지기까지의 모든 과정을<br/>까다롭고, 섬세하게 컨트롤하고 있습니다.',
        rocation: '서울특별시 마포구 마포대로 156 공덕푸르지오시티 1층 107호',
        sns: 'Instagram',
        sns_p: 'younganddaughters'
    },
    {
        id: 'cafe15',
        link: '/allRostery/rosteryDetail',
        cafeName: '식물학 커피로스터스',
        logoImg: 'logo_15.png',
        cafe_poto_01: 'poto_15_1.jpg',
        cafe_poto_02: 'poto_15_2.jpg',
        cafe_poto_03: 'poto_15_3.jpg',
        about: '"회색 빛 도심을 초록으로 물들이자"라는 이념 아래 퀄리티 높은 스페셜티 커피를 즐길 수 있는 그린 스페이스를 지향 합니다. <br/><br/>저희가 만드는 커피가 고객님들의 몸과 마음에 힐링이 되기를 소망하며 커피를 만들어가고 있습니다.',
        rocation: '서울시 강남구 강남대로154길 33',
        sns: 'Instagram',
        sns_p: 'sikmulhak'
    },
    {
        id: 'cafe16',
        link: '/allRostery/rosteryDetail',
        cafeName: '오프사이트',
        logoImg: 'logo_16.png',
        cafe_poto_01: 'poto_16_1.jpg',
        cafe_poto_02: 'poto_16_2.jpg',
        cafe_poto_03: 'poto_16_3.jpg',
        about: '[ OFF-SIGHT ] <br/>시각적 이미지는 우리에게 유용한 정보를 가져다주지만 때론 중요한 본질을 놓치게 만들기도 합니다. <br/><br/>커피를 마시는 공간, 그리고 잔 안에 담긴 음료, <br/>그 이상의 가치를 담아내기 위해 오프사이트는 오늘도 노력합니다. <br/><br/>철저하게 테스트를 거쳐 선별된 생두로 로스팅하며, 일반 소비자분들께도 충분히 설득력있는 맛을 표현해드리고자 노력합니다.',
        rocation: '경기도 고양시 일산동구 정발산동 1258-5',
        sns: 'Instagram',
        sns_p: 'offsight_official'
    },
    {
        id: 'cafe17',
        link: '/allRostery/rosteryDetail',
        cafeName: '인더매스',
        logoImg: 'logo_17.png',
        cafe_poto_01: 'poto_17_1.jpg',
        cafe_poto_02: 'poto_17_2.jpg',
        cafe_poto_03: 'poto_17_3.jpg',
        about: '우리는 좋은 커피를 만드는 사람들입니다.<br/>인더매스 로스터와 바리스타는 좋은 커피 한 잔을 위해 각 산지에서 수확한 생두가 커피 한 잔이 되기까지의 모든 과정과 결과에 집중합니다.',
        rocation: '서울 성동구 마장로 270',
        sns: 'Instagram',
        sns_p: 'inthemass_'
    },
    {
        id: 'cafe18',
        link: '/allRostery/rosteryDetail',
        cafeName: '디카프워크룸',
        logoImg: 'logo_18.png',
        cafe_poto_01: 'poto_18_1.jpg',
        cafe_poto_02: 'poto_18_2.jpg',
        cafe_poto_03: 'poto_18_3.jpg',
        about: '카페인에 민감하지만 누구보다 커피를 좋아하는 사람, 오후엔 디카페인 커피가 필요한 사람, 아기를 위해 잠시 커피를 참고 있는 사람, 누구든 언제나 맛있는 커피를 즐길 수 있으면 좋겠습니다. <br/><br/>디카프워크룸은 여러분의 디카페인 생활을 응원하며 맛있는 디카페인 커피를 연구하고 다양한 방식으로 제안합니다. <br/><br/>누구에게나 어울리는 마법 같은 디카페인 커피로 편안한 시간을 선물하겠습니다.',
        rocation: '경기도 파주시 꽃아마길 41',
        sns: 'Instagram',
        sns_p: 'decafworkroom'
    },
    {
        id: 'cafe19',
        link: '/allRostery/rosteryDetail',
        cafeName: '차군커피로스터스',
        logoImg: 'logo_19.png',
        cafe_poto_01: 'poto_19_1.jpg',
        cafe_poto_02: 'poto_19_2.jpg',
        cafe_poto_03: 'poto_19_3.jpg',
        about: '언제나 편안한 한잔이 되기를 바라는 마음으로 데일리 커피를 지향하며, 커피가 가진 캐릭터를 선명하게 표현하려 노력하는 차군커피로스터스 입니다.',
        rocation: '경상남도 밀양시 가곡7길 21',
        sns: 'Instagram',
        sns_p: 'chaguncoffee'
    },
    {
        id: 'cafe20',
        link: '/allRostery/rosteryDetail',
        cafeName: '502 커피로스터스',
        logoImg: 'logo_20.png',
        cafe_poto_01: 'poto_20_1.jpg',
        cafe_poto_02: 'poto_20_2.jpg',
        cafe_poto_03: 'poto_20_3.jpg',
        about: '(주)502커피로스터스는 2009년 설립된 스페셜티커피 로스팅 전문기업입니다. <br/><br/>최상의 커피를 제공하기 위해 엄격한 생두 선정 과정을 거치며 다년간 쌓아온 502커피로스터스만의 로스팅 기술과 철저한 품질관리를 기반으로 커피의 다양한 매력을 소개합니다. <br/><br/>커피를 마신다는 것은 단순한 행위 이상입니다. <br/>우리는 생산자와 소비자, 커피와 매개된 모든 관계를 소중히 여기며 소통합니다. <br/>한잔의 커피가 모두에게 즐거움이길 바랍니다.',
        rocation: '서울시 강남구 테헤란로 142 캐피탈타워 1층',
        sns: 'Instagram',
        sns_p: '502coffeeroasters'
    },
    {
        id: 'cafe21',
        link: '/allRostery/rosteryDetail',
        cafeName: '프로토콜 로스터스',
        logoImg: 'logo_21.jpeg',
        cafe_poto_01: 'poto_21_1.jpg',
        cafe_poto_02: 'poto_21_2.jpg',
        cafe_poto_03: 'poto_21_3.jpg',
        about: 'PROTOKOLL은 보편적으로 하루에 두 잔의 커피를 마시길 희망합니다. <br/><br/>그렇다면 한 잔은 에스프레소 머신으로 내려지고 약간은 다크하게 로스팅된 커피였으면 합니다. 매일 마셔도 지겹지 않되 임팩트가 있으며 균형감이 좋은 커피면 이상적일 겁니다. 또 다른 한 잔은 정성스레 내린 브루잉 커피이기를 희망합니다. <br/><br/>우리의 브루잉 커피는 언제 마시더라도 부담스럽지 않고 티와 같은 향을 지닌 커피일 것입니다. PROTOKOLL은 이러한 커피들을 소개하기 위해 시작되었고, 끊임없이 고민하고 기록하며 나아갈 것입니다.',
        rocation: '서울특별시 서대문구 연희로 109, 2층 프로토콜',
        sns: 'Instagram',
        sns_p: 'protokoll.roasters'
    },
    {
        id: 'cafe22',
        link: '/allRostery/rosteryDetail',
        cafeName: '링크 커피 로스터스',
        logoImg: 'logo_22.jpeg',
        cafe_poto_01: 'poto_22_1.jpg',
        cafe_poto_02: 'poto_22_2.jpg',
        cafe_poto_03: 'poto_22_3.jpg',
        about: '"We link mind to mind." 링크에프엔비는 커피가 자라는 산지에서 한 잔의 커피가 완성되는 순간까지, 커피의 모든 순간 속의 마음을 담아 원두를 로스팅 합니다. <br/>커피의 달고 시고 쓴 맛이 조화로운 밸런스가 좋은 커피, 마지막 한 모금까지 맛있는 깔끔한 커피를 만듭니다.',
        rocation: '전라남도 장성군 진원면 나노산단2로52, 205호',
        sns: 'Instagram',
        sns_p: 'linkcoffee_roasters'
    },
    {
        id: 'cafe23',
        link: '/allRostery/rosteryDetail',
        cafeName: '컬러드 빈',
        logoImg: 'logo_23.jpeg',
        cafe_poto_01: 'poto_23_1.jpg',
        cafe_poto_02: 'poto_23_2.jpg',
        cafe_poto_03: 'poto_23_3.jpg',
        about: '커피 생두에 다양한 색을 입혀, 다채로움을 추구하는 로스터리 컬러드 빈 입니다. <br/><br/>커피에는 다양성이 분명 존재합니다. 로스팅에 의한 다양성 그리고 생두에 의한 다양성인데요, 로스팅과 특별한 생두의 선택이 저희 로스터리를 더 다채롭게 만듭니다. <br/><br/>커피의 맛과 개성을 살리기 위한 로스팅을 적극적으로 활용하며, 마시는 이로 하여금 산뜻한 기분과 분명한 노트를 제공하기 위해 항상 노력합니다. <br/><br/>커피 생두에도 색을 입히듯, 음료에도 우유를 넣어 블랙이 아닌 다른 색상을 입히기도 하는데요. 저희 커피는 특히나 우유와의 조합을 항상 필두로 생각하여 최적의 로스팅과 추출 가이드를 제공합니다.',
        rocation: '서울 서대문구 연희로11가길 8-8',
        sns: 'Instagram',
        sns_p: 'coloured_bean'
    },
    {
        id: 'cafe24',
        link: '/allRostery/rosteryDetail',
        cafeName: '리플렉트 커피 로스터스',
        logoImg: 'logo_24.png',
        cafe_poto_01: 'poto_24_1.jpg',
        cafe_poto_02: 'poto_24_2.jpg',
        cafe_poto_03: 'poto_24_3.jpg',
        about: '*우리를 커피에 비추다. 우리의 색과 진심을 커피에 반영하다* <br/><br/>품질 좋은 재료를 수급 하기 위하여 시즌별로 수많은 생두를 테스트하고 가장 맛있는 생두를 사용합니다. <br/>우리의 커피는 좋은 원재료가 가지고 있는 캐릭터와 단맛을 잘 표현하기 위한 로스팅을 하고 있습니다.<br/>커피에 대한 우리의 진심이 맛으로써 전달될 수 있도록 노력하겠습니다.',
        rocation: '서울시 서초구 효령료 72길 57',
        sns: 'Instagram',
        sns_p: 'reflect_coffee'
    },
    {
        id: 'cafe25',
        link: '/allRostery/rosteryDetail',
        cafeName: '오드이븐',
        logoImg: 'logo_25.jpeg',
        cafe_poto_01: 'poto_25_1.jpg',
        cafe_poto_02: 'poto_25_2.jpg',
        cafe_poto_03: 'poto_25_3.jpg',
        about: '*당신의 일상에 색다른 쉼터*<br/>홀수와 짝수를 의미하는 오드이븐은 커피의 대중성과 전문성을 함께 하기 위해 노력하고 있습니다. <br/><br/>*누구나 편안하게 마시는 커피와 <br/>기억에 남는 커피를 전해드리는 것을 추구합니다.*<br/>한잔의 커피가 당신의 평범한 일상에 행복한 변화가 있기를 바랍니다.',
        rocation: '부산 중구 중구로29번길 7 1층 오드이븐',
        sns: 'Instagram',
        sns_p: 'oddeven_official'
    },
    {
        id: 'cafe26',
        link: '/allRostery/rosteryDetail',
        cafeName: '카페플롬',
        logoImg: 'logo_26.png',
        cafe_poto_01: 'poto_26_1.jpg',
        cafe_poto_02: 'poto_26_2.jpg',
        cafe_poto_03: 'poto_26_3.jpg',
        about: 'FLAM 노르웨이어로 플롬이라고 읽는 이곳은 노르웨이의 유명 관광지이자 아름다운 항구마을인 플롬을 사용하여 편안하고 자연친화적인 공간을 지향하고자 했습니다. <br/><br/>공간을 디자인하면서 대부분이 이곳을 방문했을때 북유럽에 왔다는 느낌을 받았으면하여 카페 내부 공간 구성, 곳곳에 놓여진 소품, 심지어 사용되는 커피잔까지도 기존의 카페와 다르게 만들었습니다. <br/><br/>카페라는 공간은 커피도 물론 중요하지만 쉬는 시간을 할애할 수 있는 자기 자신에게 가치를 부여해주는 의미있는 공간입니다. <br/><br/>여기 플롬에서 커피를 마시는 순간만큼은 바쁜 삶속에서 정말 행복하고 기억에 남게 만들어드리고 싶습니다.',
        rocation: '서울특별시 마포구 동교로38길 33 201호',
        sns: 'Instagram',
        sns_p: 'kaffe_flam'
    },
    {
        id: 'cafe27',
        link: '/allRostery/rosteryDetail',
        cafeName: '하우트 커피컴퍼니',
        logoImg: 'logo_27.png',
        cafe_poto_01: 'poto_27_1.jpg',
        cafe_poto_02: 'poto_27_2.jpg',
        cafe_poto_03: 'poto_27_3.jpg',
        about: '2009년 작은 로스터리카페로 시작한 하우트커피컴퍼니는<br/>프로밧 로스터기와 다이렉트트레이드를 통한 고품질의 생두,<br/>전문 로스터의 엄격한 품질관리로 차별화된 감각적인 커피를 생산합니다.<br/><br/>품질과 신뢰의 가치를 존중하며 다양한 스페셜티 커피와<br/>본연의 맛을 살린 로스팅으로 좋은 커피를 만들기위해 항상 노력합니다.',
        rocation: '충북 청주시 청원구 내수읍 충청대로 904',
        sns: 'Instagram',
        sns_p: 'haute_coffee_'
    },
    {
        id: 'cafe28',
        link: '/allRostery/rosteryDetail',
        cafeName: '디벨로핑룸',
        logoImg: 'logo_28.png',
        cafe_poto_01: 'poto_28_1.jpg',
        cafe_poto_02: 'poto_28_2.jpg',
        cafe_poto_03: 'poto_28_3.jpg',
        about: '‘현상하다(develop)’<br/><br/>‘develop’ 이라는 단어가 가진 의미는 다양하지만, 공통적으로 잠재되어 있던 것이 발현되는 것을 나타냄으로써 ‘가능성’을 내포하고 있습니다.<br/><br/>로스팅 과정 중 커피의 구체적인 맛의 발현이 일어나는 구간을 developing time이라고 하는 것, 아시나요? ‘develop’이 가진 의미를 공간에 담아내어 developing room이 되었습니다.<br/><br/>디벨로핑룸은 각각의 커피가 가진 잠재적인 색과 뉘앙스를 체계적 로스팅을 통해 구체적으로 밝혀내는 역할을 합니다.<br/><br/>화려하거나 호화롭진 않지만 소박하면서도 매력적인 공간을 지향하는 디벨로핑룸은 번화가가 아닌 인천의 구석진 곳에 자리를 잡았습니다. 어디서 본듯한 유행이 아닌 우리의 고유한 개성을 공간에 반영하고자 직접 매장을 꾸미고, 꾸밈없고 편안한 느낌을 커피와 함께 공유하고 싶은 스페셜티 커피 로스터리입니다.<br/><br/>대형 로스터리와 홍대 소재의 스페셜티 매장에서의 경험으로 가장 중요하게 생각해온 것은 커피의 재현성입니다.<br/><br/>최고의 퀄리티를 내는 것 이상으로 중요한 로스팅 결과물의 동일성을 중점 컨트롤 하며, 이를위해 프로파일을 철저히 기록하고 관리합니다. 디벨로핑룸은 디드릭사의 로스터기를 사용하여 높은 전도비율을 장점으로 농밀한 단맛과 클린컵에 집중하는 커피를 만들어 내고 있습니다.',
        rocation: '인천광역시 연수구 청명로 26',
        sns: 'Instagram',
        sns_p: 'developingroom'
    },
    {
        id: 'cafe29',
        link: '/allRostery/rosteryDetail',
        cafeName: '안녕 가비 커피로스터스',
        logoImg: 'logo_29.png',
        cafe_poto_01: 'poto_29_1.jpg',
        cafe_poto_02: 'poto_29_2.jpg',
        cafe_poto_03: 'poto_29_3.jpg',
        about: '그냥 커피가 아니라 누가 어떤 노력으로 어떠한 자연환경에서 생산된 특별한 커피인지 구체적인 이야기를 소비자분들에게 정직하게 들려주고, 그곳 생산자 농부들의 이야기는 진심으로 들어주는.<br/><br/>품질 좋은 커피를 지속 가능하게 정성껏 만들어 안녕가비커피로스터스를 선택해주신 고마운 누군가에게 커피 한잔을 마실 때에는 행복함과 충만감을 선사하고 다 드시고 난 뒤에는 그리움으로 남아 결국엔 다시 찾게 되는 그런 기억되고 잊히지 않는 커피를 만들어 드리겠습니다.',
        rocation: '서울시 광진구 능동로53길 41 1층',
        sns: 'Instagram',
        sns_p: 'hellogabi2012'
    },
    {
        id: 'cafe30',
        link: '/allRostery/rosteryDetail',
        cafeName: '브니엘 커피로스터스',
        logoImg: 'logo_30.png',
        cafe_poto_01: 'poto_30_1.jpg',
        cafe_poto_02: 'poto_30_2.jpg',
        cafe_poto_03: 'poto_30_3.jpg',
        about: '브니엘 커피 로스터스는 스페셜티 커피업이 지향하는 지속가능성을 산지 농부들에게만 관심을 두는 것이 아니라 이 땅의 소외받는 약자들에게 실현하는 것을 목표로 세운 회사입니다.<br/>"컵에서 신의 얼굴을 보았다" 게이샤 커피가 등장했을 때 심사위원이 했던 저 말처럼 스페셜티 커피를 처음 접하는 사람들께 같은 감동을 드리기 위해 노력합니다.',
        rocation: '서울특별시 양천구 신월동 150-14',
        sns: 'Instagram',
        sns_p: 'penielcoffee'
    },
    {
        id: 'cafe31',
        link: '/allRostery/rosteryDetail',
        cafeName: '프레이저 커피',
        logoImg: 'logo_31.png',
        cafe_poto_01: 'poto_31_1.jpg',
        cafe_poto_02: 'poto_31_2.jpg',
        cafe_poto_03: 'poto_31_3.jpg',
        about: '프레이저 커피는 숲과 바다, 해변, 자연이 어우러진 지상낙원이라 불리는 프레이저 아일랜드를 모티프로 시작되었습니다.<br/><br/>한잔의 커피를 즐기는 이 순간, 일상의 여유와 함께 기억될만한 추억으로 만들어주고 우리의 가치와 철학이 고스란히 전해지길 원합니다.',
        rocation: '경기 성남시 분당구 구미로9번길 25',
        sns: 'Instagram',
        sns_p: 'frasercoffeeco'
    },
    {
        id: 'cafe32',
        link: '/allRostery/rosteryDetail',
        cafeName: 'BACS',
        logoImg: 'logo_32.png',
        cafe_poto_01: 'poto_32_1.jpg',
        cafe_poto_02: 'poto_32_2.jpg',
        cafe_poto_03: 'poto_32_3.jpg',
        about: "Barista's Choices, BACS는, 여러분들에게 맛있는 커피 한 잔으로 즐겁고 행복한 하루를 선물하기 위해 탄생한 브랜드입니다.<br/><br/>서초동의 작은 로스터리 카페에서 출발한지 약 10년, 세월속에 녹아든 경험과 실력을 바탕으로 바리스타가 선택한 최고의 커피를 소개드립니다.",
        rocation: '서울 서초구 서초대로 397 104호',
        sns: 'Instagram',
        sns_p: 'bacspresso_official'
    },
]

export default all_rostery